WindowsEventLog: Multiple Updates - Fixes #355, #349, #338, #229
dsccommunity/ComputerManagementDsc pull request #359
Opened 2021-02-12 14:50 UTC by cohdjn

#### Pull Request (PR) description
    Multiple Updates for WindowsEventLog

#### This Pull Request (PR) fixes the following issues
    - Fixes #229
    - Fixes #338
    - Fixes #349 
    - Fixes #355 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2021-02-21 06:08 UTC, cohdjn commented
@PlagueHO Any ETA on when you'll be able to do the code review?  Anything I can do to help?

2021-02-21 06:27 UTC, PlagueHO commented
Hi @cohdjn - sorry about the delay. I'll be back on this week with reviews. Can you resolve the conflicts on this one?

2021-02-21 08:31 UTC, cohdjn commented
@PlagueHO I never had this problem before so I _hope_ I fixed the conflict correctly!  I'm still quite the newbie at all this but I'm learning!  :)

2021-02-22 05:21 UTC, PlagueHO commented
/azurepipelines run

2021-02-22 06:27 UTC, PlagueHO requested changes
> Reviewed 9 of 16 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 10 of 16 files reviewed, 7 unresolved discussions (waiting on @cohdjn)

___
*[CHANGELOG.md, line 17 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7Ez2SDRaxVfLwfTeq:-MU7Ez2SDRaxVfLwfTer:b-qkcmsz) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/CHANGELOG.md#L17)):*
> ```Markdown
> ### Changed
> 
> - ScheduledTask
> ```

Can you remove this block of changes as it also appears under ### Fixed?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 33 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7GhQD1wQFYGtu9jlB:-MU7GhQD1wQFYGtu9jlC:b-uvm3h3) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L33)):*
> ```PowerShell
>         $LogName,
> 
>         [Parameter()]
> ```

We shouldn't pass any parameters except for ones that are defined as `Write` and `Key` in the MOF file. Can we change the resource so that the `Get-WindowsEventLogRegisteredSource` to support this?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 60 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7HZln9N_OETwRJcVT:-MU7HZln9N_OETwRJcVU:b-66ood5) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L60)):*
> ```PowerShell
>     }
> 
>     if ($PSBoundParameters.ContainsKey('RegisteredSource'))
> ```

As above, we shouldn't pass the `RegisteredSource` to this method. Is there a way we can determine the Registered Source parameters without having to pass the SourceName in the first call?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 257 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7OEBKBBTDvcUkrlZb:-MU7OEBKBBTDvcUkrlZc:blgds84) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L257)):*
> ```PowerShell
>     }
> 
>     if ($PSBoundParameters.ContainsKey('RegisteredSource'))
> ```

What would happen
___
*[source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1, line 39 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7PZDIABxasBGXoeHp:-MU7PZDIABxasBGXoeHq:b-t097of) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1#L39)):*
> ```PowerShell
> }
> 
> <#
> ```

Can we split this into another file? These get automatically published to the PS Gallery as DSC scripts so need to be in separate files.
___
*[source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1, line 68 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7Pey85p_9YhduQ4a6:-MU7Pey92_h3r89bd4ln:b-t097of) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1#L68)):*
> ```PowerShell
> }
> 
> <#
> ```

Can we split this into another file? These get automatically published to the PS Gallery as DSC scripts so need to be in separate files.
___
*[source/Examples/Resources/WindowsEventlog/7-WindowsEventLog_RestrictGuestAccess_Config.ps1, line 39 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7PmcC4ddB1BGsACjA:-MU7PmcC4ddB1BGsACjB:b-t097of) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/Examples/Resources/WindowsEventlog/7-WindowsEventLog_RestrictGuestAccess_Config.ps1#L39)):*
> ```PowerShell
> }
> 
> <#
> ```

Can we split this into another file? These get automatically published to the PS Gallery as DSC scripts so need to be in separate files.


<!-- Sent from Reviewable.io -->

2021-02-22 06:40 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 10 of 16 files reviewed, 7 unresolved discussions (waiting on @cohdjn and @PlagueHO)

___
*[CHANGELOG.md, line 17 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7Ez2SDRaxVfLwfTeq:-MU7SgN648Mwdd2hy1fI:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/CHANGELOG.md#L17)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove this block of changes as it also appears under ### Fixed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-22 07:02 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 10 of 16 files reviewed, 7 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 33 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7GhQD1wQFYGtu9jlB:-MU7TaeM7rJOQZACacqg:b-jewjfq) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L33)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

We shouldn't pass any parameters except for ones that are defined as `Write` and `Key` in the MOF file. Can we change the resource so that the `Get-WindowsEventLogRegisteredSource` to support this?
</blockquote></details>

The MOF has RegisteredSource as a Write value.  Maybe I'm confused what you're looking for here?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 60 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7HZln9N_OETwRJcVT:-MU7TzQ_2wK_beuIgDNJ:beoip21) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L60)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

As above, we shouldn't pass the `RegisteredSource` to this method. Is there a way we can determine the Registered Source parameters without having to pass the SourceName in the first call?
</blockquote></details>

Please refer back to my comment above.  I'm not sure I understand what I'm doing wrong or what you'd like to see changed?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 257 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7OEBKBBTDvcUkrlZb:-MU7UVzeAyaV-OA8JVaY:b-oh3f0c) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L257)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

What would happen
</blockquote></details>

I don't understand.
___
*[source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1, line 39 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7PZDIABxasBGXoeHp:-MU7XsJJC2LLECgYQEMo:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1#L39)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we split this into another file? These get automatically published to the PS Gallery as DSC scripts so need to be in separate files.
</blockquote></details>

Done.
___
*[source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1, line 68 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7Pey85p_9YhduQ4a6:-MU7XtOT6NNm0Lbe94OB:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/Examples/Resources/WindowsEventlog/6-WindowsEventLog_RegisterEventSource_Config.ps1#L68)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we split this into another file? These get automatically published to the PS Gallery as DSC scripts so need to be in separate files.
</blockquote></details>

Done.
___
*[source/Examples/Resources/WindowsEventlog/7-WindowsEventLog_RestrictGuestAccess_Config.ps1, line 39 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7PmcC4ddB1BGsACjA:-MU7XuSoE606MnJMjRFu:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/Examples/Resources/WindowsEventlog/7-WindowsEventLog_RestrictGuestAccess_Config.ps1#L39)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we split this into another file? These get automatically published to the PS Gallery as DSC scripts so need to be in separate files.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-24 05:08 UTC, PlagueHO requested changes
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 8 of 19 files reviewed, 6 unresolved discussions (waiting on @cohdjn and @PlagueHO)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 33 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7GhQD1wQFYGtu9jlB:-MUHQg179wHO2_lMXlUT:boviqh4) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L33)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

The MOF has RegisteredSource as a Write value.  Maybe I'm confused what you're looking for here?
</blockquote></details>

Doh! I apologize - I meant `Required` and `Key`. Had done a lot of reviews that day :cry:


<!-- Sent from Reviewable.io -->

2021-02-26 06:00 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 8 of 19 files reviewed, 6 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 33 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7GhQD1wQFYGtu9jlB:-MURt6Wc-Vg-8iVcLcl6:bqmu104) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L33)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Doh! I apologize - I meant `Required` and `Key`. Had done a lot of reviews that day :cry:
</blockquote></details>

I removed RegisteredSource. I couldn't see a way to make this work within the constraints you requested.


<!-- Sent from Reviewable.io -->

2021-02-26 06:51 UTC, cohdjn commented
@PlagueHO The integration test bombed outside of this resource. I don't know what I should do at this point?

2021-02-26 06:56 UTC, PlagueHO commented
/azuredevops run

2021-02-26 06:57 UTC, PlagueHO commented
/AzurePipelines run

2021-02-26 07:28 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 8 of 19 files reviewed, 6 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 33 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7GhQD1wQFYGtu9jlB:-MUSEEusEU9g53GCv3UV:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L33)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

I removed RegisteredSource. I couldn't see a way to make this work within the constraints you requested.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 07:29 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 8 of 19 files reviewed, 6 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 60 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7HZln9N_OETwRJcVT:-MUSEPd60k3C1e3KW1pz:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L60)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

Please refer back to my comment above.  I'm not sure I understand what I'm doing wrong or what you'd like to see changed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 07:32 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 8 of 19 files reviewed, 6 unresolved discussions (waiting on @PlagueHO)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 257 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MU7OEBKBBTDvcUkrlZb:-MUSFACd0_fKP2JbZqI9:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/df965d7e6c189c3bfa098c5348a0966f3116912d/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L257)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

I don't understand.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-03 15:42 UTC, cohdjn commented
@PlagueHO Have you been able to finish the code review?  Anything else you see that should be changed/fixed?

2021-03-03 19:38 UTC, PlagueHO commented
Hi @cohdjn - sorry about the delay. Been snowed under with my day job this week. I'll be onto it this weekend.

2021-04-04 23:49 UTC, PlagueHO requested changes
Really sorry about the really long delay @cohdjn - I had to take a month off DSC due to day job taking all capacity. Just some minor tweaks - nothing major, then will merge.

> Reviewed 4 of 16 files at r1, 6 of 7 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-:-MXU36eK6oDVE2povnQY:b-y6wfb7)* status: all files reviewed, 22 unresolved discussions (waiting on @cohdjn)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 467 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU004Q5fhPNTIIECVq:-MXU004R60DMGUdLgQmv:b7bgyfp) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L467)):*
> ```PowerShell
>             -SourceName $RegisteredSource
> 
>         $currentCategoryResourceFile = Get-WindowsEventLogRegisteredSourceFile `
> ```

FYI: Could probably improve the performance here by getting `Get-WindowsEventLogRegisteredSourceFile` to return an object with properties for each ResourceFileType. Can do this in future, no need to change this PR.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 529 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU0gWO9nq5apxn3OXP:-MXU0gWP3oe4ny6-fju9:b-o2wa6h) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L529)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose? E.g. 'Get windows event log or throw an exception if it does not exist'
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 560 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU0y8yEDB3NjvfhFwt:-MXU0y8z3EuvlwdKUBn1:bqn8ytu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L560)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 598 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1-SM5lhGhr18yhPn:-MXU1-SM5lhGhr18yhPo:bqn8ytu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L598)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 630 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1ZY82_b1bWhmLUkz:-MXU1ZY82_b1bWhmLUl-:b-k3bslw) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L630)):*
> ```PowerShell
>     )
> 
>     $file = ''
> ```

Can you add blank line after this one?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 667 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1buyDTi2waJ-xbYM:-MXU1buyDTi2waJ-xbYN:bqn8ytu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L667)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 684 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU2-9vAM1PzTjS2Ckp:-MXU2-9wB5xCNhF3xtni:b-10emr9) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L684)):*
> ```PowerShell
> 
>     $eventLogRegistryPath = 'HKLM:\SYSTEM\CurrentControlSet\Services\EventLog'
>     $logRegistryPath = Join-Path -Path $eventLogRegistryPath -ChildPath $LogName
> ```

Can you add a blank line after this one?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 694 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1r7zCg1wtMIWNogG:-MXU1r7zCg1wtMIWNogH:b47xm2q) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L694)):*
> ```PowerShell
>     }
> 
>     if ($logProperties.RestrictGuestAccess -eq 1)
> ```

Could you convert this to:
```powershell
retrurn ($logProperties.RestrictGuestAccess -eq 1)
```
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 706 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU26pj8Ss2gVmp3RUN:-MXU26pj8Ss2gVmp3RUO:b-u7ghgg) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L706)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose? Sorry, I realize this is an existing function so should have been corrected already.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 736 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU2DFR-11yYNHNjrp-:-MXU2DFR-11yYNHNjrp0:bqn8ytu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L736)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 781 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU2OBy55hhOl2LjxVj:-MXU2OBz1MCtr3_SSQHl:b-47vc1q) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L781)):*
> ```PowerShell
>     foreach ($file in $CategoryResourceFile, $MessageResourceFile, $ParameterResourceFile)
>     {
>         if ($file -ne '' -and -not (Test-Path -Path $file -IsValid))
> ```

Can you use `-not [System.String]::IsNullOrEmpty($file)` to check that $file is not empty?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 829 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU3OfFApj6DVhjgSDr:-MXU3OfGA30Miwe3QCch:bqn8ytu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L829)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 857 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU3SbP39uI-A2kGKK0:-MXU3SbP39uI-A2kGKK1:bqn8ytu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L857)):*
> ```PowerShell
> <#
>     .SYNOPSIS
>         Helper function for WindowsEventLog.
> ```

Can this describe the function purpose?
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm [...]

2021-04-06 05:21 UTC, cohdjn commented
I _think_ I got everything requested.  Just lemme know if there's anything else you see amiss.  And please continue to nitpick... the only way I'm going to learn and get better is through this kind of iterative process and I appreciate it!

2021-04-06 06:20 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 17 of 19 files reviewed, 21 unresolved discussions (waiting on @cohdjn and @PlagueHO)

___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 529 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU0gWO9nq5apxn3OXP:-MX_p_5JEU6HXft_r4km:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L529)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose? E.g. 'Get windows event log or throw an exception if it does not exist'
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 560 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU0y8yEDB3NjvfhFwt:-MX_p_zR9Qhw0f4215KP:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L560)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 598 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1-SM5lhGhr18yhPn:-MX_pacn2HPaqps6BMjW:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L598)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 630 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1ZY82_b1bWhmLUkz:-MX_pbUs3BGTUAjMP2-1:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L630)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add blank line after this one?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 667 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1buyDTi2waJ-xbYM:-MX_pcA6CBUMofXh9-CX:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L667)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 684 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU2-9vAM1PzTjS2Ckp:-MX_pdNQBE9-YODHRFCm:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L684)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line after this one?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 694 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU1r7zCg1wtMIWNogG:-MX_peJd-aJYiu-Gp49s:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L694)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you convert this to:
```powershell
retrurn ($logProperties.RestrictGuestAccess -eq 1)
```
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 706 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU26pj8Ss2gVmp3RUN:-MX_pepl1mcWBFj1xBG8:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L706)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose? Sorry, I realize this is an existing function so should have been corrected already.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 736 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU2DFR-11yYNHNjrp-:-MX_pgAm-ddjVXtUAxAo:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L736)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 781 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU2OBy55hhOl2LjxVj:-MX_pi7N5WB3OIsx_pRV:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L781)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use `-not [System.String]::IsNullOrEmpty($file)` to check that $file is not empty?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 829 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU3OfFApj6DVhjgSDr:-MX_pjLGANrAA6sZLCdI:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L829)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 857 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU3SbP39uI-A2kGKK0:-MX_pjuG4CkplSwzFmZw:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L857)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1, line 914 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXU8mZFErPGqKrwwC-4:-MX_pm0vDLdBTygrgb7l:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/source/DSCResources/DSC_WindowsEventLog/DSC_WindowsEventLog.psm1#L914)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this describe the function purpose?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-06 06:21 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 17 of 19 files reviewed, 19 unresolved discussions (waiting on @cohdjn and @PlagueHO)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 186 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUB0Uu-PP6vJsUxRhF:-MX_prec1GyhMinVsawi:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L186)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we check the error is the one expected? E.g.
```powershell
                   $errorMessage = $script:localizedData.GetWindowsEventLogFailure -f 'UndefinedLog`
                   { Get-TargetResource `
                        -LogName 'UndefinedLog' `
                        -Verbose
                    } | Should -Throw $errorMessage
```
</blockquote></details>

Done.
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 206 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUFEckB2WC46oQAa4D:-MX_ptJIA1EFP914SrKy:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L206)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we validate the values of what is returned as the required functions are mocked, so we should return expected values.
</blockquote></details>

Done.
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 225 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUFfVW8nenePnVqaRC:-MX_ptw7CLpfMBqPtY5t:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L225)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we validate error is expected one?
</blockquote></details>

Done.
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 242 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUFkbO-F2SpeuxlJI-:-MX_pvWD4k3eiwk43u6h:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L242)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we validate error is expected one? And throughout?
</blockquote></details>

Done.
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 553 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUG8czBY7x478DspIb:-MX_pyeH8TsAzM2wOG8O:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L553)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we validate error is expected one? And throughout - it may not always be possible, but if it is a custom error we're throwing we should be able to.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-06 06:22 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: 17 of 19 files reviewed, 19 unresolved discussions (waiting on @PlagueHO)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 503 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUGjCNEUti94sQNNBa:-MX_q3EUCaJwI2PoEbvq:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L503)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should also mock `Mock -CommandName Get-ItemProperty` but just leave the `-MockWith` out (to return $null). Otherwise the test will look at the local machine registry and so the test is not deterministic.
</blockquote></details>

Done.
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 553 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUG8czBY7x478DspIb:-MX_q4dk340Dh0bWufoO:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L553)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-09 07:34 UTC, PlagueHO requested changes
Looking awesome @cohdjn  - just some minor tweaks to validate errors occur in the expected placed and then will merge :grin: thanks again for putting up with the nitpicks and time to review!

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-:-MXpYDNL1f4mpLfr6Mf5:b1r2qwv)* status: all files reviewed, 2 unresolved discussions (waiting on @cohdjn)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 186 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUB0Uu-PP6vJsUxRhF:-MXpVhCeD9MPaBuhqt_g:bpc7dqm) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L186)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This test seems to have been removed - was that intentional?
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 220 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXpXMZLCzxoQaTDmsjt:-MXpXMZLCzxoQaTDmsju:bhyfpqg) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/90049e19c75076257ae3ac223119ee2660bdac66/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L220)):*
> ```PowerShell
> 
>                 It 'Should throw when MaximumSizeInBytes is less than 64KB' {
>                     { Test-TargetResource -LogName 'Application' -MaximumSizeInBytes 0 } | Should -Throw
> ```

The error records doesn't appear to be validated for the next few tests - is that correct?

E.g.

```powershell
                  $errorRecord = Get-InvalidArgumentRecord `
                    -Message ($localizedData.InvalidSystemLocaleError -f $script:badSystemLocale) `
                    -ArgumentName 'SystemLocale'
                It 'Should throw expected error when MaximumSizeInBytes is less than 64KB' {
                    { Test-TargetResource -LogName 'Application' -MaximumSizeInBytes 0 } | Should -Throw $errorRecord
                }
```

See: https://github.com/dsccommunity/ComputerManagementDsc/blob/307bcb8600b814d6f6d124a79097ddede718c779/tests/Unit/DSC_SystemLocale.Tests.ps1#L113

Or can these exceptions not be validated?
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 529 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXpXlIlDjnLFCjCeCOa:-MXpXlIlDjnLFCjCeCOb:b-a48vrs) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/90049e19c75076257ae3ac223119ee2660bdac66/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L529)):*
> ```PowerShell
> 
>                 It 'Should throw when the New-EventLog cmdlet encounters an error' {
>                     Mock -CommandName New-EventLog -MockWith { throw }
> ```

Can you throw a dummy message and check for that? This just ensures that the error is occurring in the place we expect.

e.g.
```powershell
                    Mock -CommandName New-EventLog -MockWith { throw 'Event Log Error' }
                    { Register-WindowsEventLogSource -LogName 'Application' -SourceName 'PesterTest' } | Should -Throw 'Event Log Error'
```

And throughout the remaining tests?


<!-- Sent from Reviewable.io -->

2021-04-09 08:16 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: all files reviewed, 2 unresolved discussions (waiting on @cohdjn)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 186 at r4](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXUB0Uu-PP6vJsUxRhF:-MXph4sc6XrVpxeV1QoM:bg11i2l) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ff39926c11720be809ad8f9616379effc086173b/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L186)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This test seems to have been removed - was that intentional?
</blockquote></details>

No that wasn't intentional!  Thank you for catching it!!


<!-- Sent from Reviewable.io -->

2021-04-09 08:20 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: all files reviewed, 2 unresolved discussions (waiting on @cohdjn and @PlagueHO)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 220 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXpXMZLCzxoQaTDmsjt:-MXphcJV34o5W8grMf0e:bjarybl) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/90049e19c75076257ae3ac223119ee2660bdac66/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L220)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

The error records doesn't appear to be validated for the next few tests - is that correct?

E.g.

```powershell
                  $errorRecord = Get-InvalidArgumentRecord `
                    -Message ($localizedData.InvalidSystemLocaleError -f $script:badSystemLocale) `
                    -ArgumentName 'SystemLocale'
                It 'Should throw expected error when MaximumSizeInBytes is less than 64KB' {
                    { Test-TargetResource -LogName 'Application' -MaximumSizeInBytes 0 } | Should -Throw $errorRecord
                }
```

See: https://github.com/dsccommunity/ComputerManagementDsc/blob/307bcb8600b814d6f6d124a79097ddede718c779/tests/Unit/DSC_SystemLocale.Tests.ps1#L113

Or can these exceptions not be validated?
</blockquote></details>

I don't know how the tests can be validated.  I have a ValidateSet on the parameter so I don't know how to properly test for what will be thrown.  I'm open to suggestions if there's a way to do it?


<!-- Sent from Reviewable.io -->

2021-04-09 08:25 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: all files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 529 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXpXlIlDjnLFCjCeCOa:-MXpizelB0SF1o4YP_jU:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/90049e19c75076257ae3ac223119ee2660bdac66/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L529)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you throw a dummy message and check for that? This just ensures that the error is occurring in the place we expect.

e.g.
```powershell
                    Mock -CommandName New-EventLog -MockWith { throw 'Event Log Error' }
                    { Register-WindowsEventLogSource -LogName 'Application' -SourceName 'PesterTest' } | Should -Throw 'Event Log Error'
```

And throughout the remaining tests?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-09 08:26 UTC, cohdjn reviewed
Committing...

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-:-MXpj8s_CY-RvjVLpRrB:bovqn50)* status: all files reviewed, 2 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2021-04-09 08:28 UTC, PlagueHO requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: all files reviewed, 1 unresolved discussion (waiting on @cohdjn)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 220 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXpXMZLCzxoQaTDmsjt:-MXpjaggDHGQA5sWSu54:bdy1izj) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/90049e19c75076257ae3ac223119ee2660bdac66/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L220)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

I don't know how the tests can be validated.  I have a ValidateSet on the parameter so I don't know how to properly test for what will be thrown.  I'm open to suggestions if there's a way to do it?
</blockquote></details>

Ahhhh - I didn't realize these were being picked up by [Validate] - so ignore this then.
___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 529 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXpXlIlDjnLFCjCeCOa:-MXpjk3l2LGYzcNMb1Ko:bbdi9gx) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/90049e19c75076257ae3ac223119ee2660bdac66/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L529)):*
<details><summary><i>Previously, cohdjn (David Nelson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Have the changes been pushed?


<!-- Sent from Reviewable.io -->

2021-04-09 08:34 UTC, cohdjn reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[tests/Unit/DSC_WindowsEventLog.Tests.ps1, line 529 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-MXpXlIlDjnLFCjCeCOa:-MXpkyX9Cn7fPBI-P1vE:b4u7w5o) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/90049e19c75076257ae3ac223119ee2660bdac66/tests/Unit/DSC_WindowsEventLog.Tests.ps1#L529)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Have the changes been pushed?
</blockquote></details>

It will be shortly.  I ran into a problem after running the build script one last time throwing errors.  I'm trying to get that fixed up now.


<!-- Sent from Reviewable.io -->

2021-04-09 09:49 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I'll merge once the tests pass. Thank you again!

> Reviewed 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359#-:-MXq1BeC2sFFVkke5bk_:bkftjqn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cohdjn)



<!-- Sent from Reviewable.io -->

2021-04-09 09:51 UTC, cohdjn commented
Awesome!  Thanks again buddy!!

2021-04-09 09:53 UTC, PlagueHO approved these changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cohdjn)



<!-- Sent from Reviewable.io -->

2021-04-09 10:06 UTC, merged