Adding Options parameter to Computer resource
dsccommunity/ComputerManagementDsc pull request #381
Opened 2022-04-07 18:39 UTC by nickgw

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

2022-04-07 20:39 UTC, PlagueHO commented
Hi @nickgw - it looks like the pipelines are broken. I'll fix these this weekend so that the CI can run on your build. But in the meantime I'll do a quick review of your PR to get you some suggestions. Thank you for submitting!

2022-04-07 21:04 UTC, nickgw commented on source/DSCResources/DSC_Computer/DSC_Computer.psm1
> +                                    New-InvalidOperationException -Message "PasswordPass is valid only when teh UnsecuredJoin option is specified"
I'm not 100% on how I should be using these error functions if you've got a quick doc on it.

2022-04-07 21:17 UTC, PlagueHO requested changes
Although the `Set` has been updated, it looks like there would need to be code added to the `Test`. In this case I'd recommend using the `Compare-Object` command to compare the two array of strings.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-:-N-4lIzI5gT2rJ-Z7tSB:b-oxzh88)* status: all files reviewed, 6 unresolved discussions (waiting on @nickgw)

___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 90 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4kLn-0NRE0XtCRcCw:-N-4kLn-0NRE0XtCRcCx:b1hkq7d) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/21022b1eaa040eb068be4c0475307fb8eb1c9a35/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L90)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.String()]
> ```

I think this should be an array of strings. That way you can also specify `ValidateSet()` to ensure the values are valid.



_Code snippet:_
```PowerShell
[ValidateSet('AccountCreate','Win9XUpgrade','UnsecuredJoin','PasswordPass','JoinWithNewName','JoinReadOnly','InstallInvoke')]
[System.String[]]
```
___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 198 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4kUyABY-3kGWx6OeH:-N-4kUyB5LeIQlZQkxod:b1hkq7d) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/21022b1eaa040eb068be4c0475307fb8eb1c9a35/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L198)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.String()]
> ```

I think this should be an array of strings. That way you can also specify `ValidateSet()` to ensure the values are valid.



_Code snippet:_
```PowerShell
[ValidateSet('AccountCreate','Win9XUpgrade','UnsecuredJoin','PasswordPass','JoinWithNewName','JoinReadOnly','InstallInvoke')]
[System.String[]]
```
___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 263 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4lkenAGsp_335oGDg:-N-4lkenAGsp_335oGDh:b-qfiawe) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/21022b1eaa040eb068be4c0475307fb8eb1c9a35/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L263)):*
> ```PowerShell
>                     #>
>                     $joinOptions = New-Object System.Collections.Generic.List[string]
>                     $available_options = @("AccountCreate","Win9XUpgrade","UnsecuredJoin","PasswordPass","JoinWithNewName","JoinReadOnly","InstallInvoke")
> ```

I think this whole block can be simplified a lot if the parameter is changed to an array of strings.

The validation for the `PasswordPass` is still needed, but you could move this whole block out into an a new `Assert-ResourceProperty` function that validates the combination. Like we do here: https://github.com/dsccommunity/NetworkingDsc/blob/main/source/DSCResources/DSC_Route/DSC_Route.psm1#L571
___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 273 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4mzWY7oxu3oS-Gtb_:-N-4mzWY7oxu3oS-Gtba:bbkdg63) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/21022b1eaa040eb068be4c0475307fb8eb1c9a35/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L273)):*
> ```PowerShell
>                                     }
>                                 } else {
>                                     New-InvalidOperationException -Message "PasswordPass is valid only when teh UnsecuredJoin option is specified"
> ```

Can this message be defined in the localization file for en-us and referenced (e.g. `$script:localizedData.InvalidOptionPasswordPassUnsecuredJoin`) ? Also, regarding the wording, it is helpful to specify the parameter first e.g.: `Domain Join option "PasswordPass" may not be specified if "UnsecuredJoin" is specified.`

You would probably use `New-InvalidArgumentOperation` here and can then specify the parameter name: https://github.com/dsccommunity/DscResource.Common#new-invalidargumentexception
___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 273 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4Jr5OYcyu5Gec9yob-r2-273:-N-4s_t02IO9zqzwdtnW:b-mkx5rz) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/222fad03ebfc03829c004fb43a31bb2f5f9eeb25/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L273)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

I'm not 100% on how I should be using these error functions if you've got a quick doc on it.
</blockquote></details>

You're using the error functions correctly - just need to use a localization string. I've added comments and links to docs above.
___
*[source/DSCResources/DSC_Computer/DSC_Computer.schema.mof, line 12 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4siZF0h92PMmgOlEr:-N-4siZF0h92PMmgOlEs:b77mg0h) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/222fad03ebfc03829c004fb43a31bb2f5f9eeb25/source/DSCResources/DSC_Computer/DSC_Computer.schema.mof#L12)):*
> ```
>     [Write, Description("The value assigned here will be set as the local computer description.")] String Description;
>     [Write, Description("The Active Directory Domain Controller to use to join the domain")] String Server;
>     [Write, Description("Specifies advanced options for the Add-Computer join operation")] String Options;
> ```

I think this should be an array of strings too. That way you can also add `ValueMap{""AccountCreate","Win9XUpgrade","UnsecuredJoin","PasswordPass","JoinWithNewName","JoinReadOnly","InstallInvoke"}, Values{"AccountCreate","Win9XUpgrade","UnsecuredJoin","PasswordPass","JoinWithNewName","JoinReadOnly","InstallInvoke"}` to the MOF.


<!-- Sent from Reviewable.io -->

2022-04-07 22:53 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 90 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4kLn-0NRE0XtCRcCw:-N-5Db9jAC9GWJo94csq:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/21022b1eaa040eb068be4c0475307fb8eb1c9a35/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L90)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this should be an array of strings. That way you can also specify `ValidateSet()` to ensure the values are valid.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 198 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4kUyABY-3kGWx6OeH:-N-5DcXq-8xgQuM5FNq2:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/21022b1eaa040eb068be4c0475307fb8eb1c9a35/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L198)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this should be an array of strings. That way you can also specify `ValidateSet()` to ensure the values are valid.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_Computer/DSC_Computer.psm1, line 273 at r1](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4mzWY7oxu3oS-Gtb_:-N-5Dj_zEiFX4A6HSK8Y:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/21022b1eaa040eb068be4c0475307fb8eb1c9a35/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L273)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this message be defined in the localization file for en-us and referenced (e.g. `$script:localizedData.InvalidOptionPasswordPassUnsecuredJoin`) ? Also, regarding the wording, it is helpful to specify the parameter first e.g.: `Domain Join option "PasswordPass" may not be specified if "UnsecuredJoin" is specified.`

You would probably use `New-InvalidArgumentOperation` here and can then specify the parameter name: https://github.com/dsccommunity/DscResource.Common#new-invalidargumentexception
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_Computer/DSC_Computer.schema.mof, line 12 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-4siZF0h92PMmgOlEr:-N-5DkPi3lJgIb_qqdfH:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/222fad03ebfc03829c004fb43a31bb2f5f9eeb25/source/DSCResources/DSC_Computer/DSC_Computer.schema.mof#L12)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this should be an array of strings too. That way you can also add `ValueMap{""AccountCreate","Win9XUpgrade","UnsecuredJoin","PasswordPass","JoinWithNewName","JoinReadOnly","InstallInvoke"}, Values{"AccountCreate","Win9XUpgrade","UnsecuredJoin","PasswordPass","JoinWithNewName","JoinReadOnly","InstallInvoke"}` to the MOF.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-10 07:05 UTC, PlagueHO commented
Once this PR (https://github.com/dsccommunity/ComputerManagementDsc/pull/384) is merged you should be able to rebase and the pipeline will work.

2022-04-12 04:36 UTC, PlagueHO commented
Hey @nickgw - your unit tests are failing because this `Get-InvalidArgumentException` should be `Get-InvalidArgumentRecord`.

2022-04-12 04:38 UTC, PlagueHO requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[tests/Unit/DSC_Computer.Tests.ps1, line 1099 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-R2ycM1cEQm2p95mXJ:-N-R2ycN9hjFKJo8nwvz:b4kfkun) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9b6136fe1f67dbd3918c897bfc348186ce1ffed3/tests/Unit/DSC_Computer.Tests.ps1#L1099)):*
> ```PowerShell
> 
>                 It 'Should throw if PasswordPass is present in options without UnsecuredJoin' {
>                     $errorRecord = Get-InvalidArgumentException `
> ```

Should be:



_Code snippet:_
```PowerShell
Get-InvalidArgumentRecord
```
___
*[tests/Unit/DSC_Computer.Tests.ps1, line 1122 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-R34hC6WZhbDq1XOYK:-N-R34hC6WZhbDq1XOYL:b4kfkun) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9b6136fe1f67dbd3918c897bfc348186ce1ffed3/tests/Unit/DSC_Computer.Tests.ps1#L1122)):*
> ```PowerShell
> 
>                 It 'Should throw if PasswordPass and UnsecuredJoin is present but credential username is not null' {
>                     $errorRecord = Get-InvalidArgumentException `
> ```

Should be:



_Code snippet:_
```PowerShell
Get-InvalidArgumentRecord
```


<!-- Sent from Reviewable.io -->

2022-04-12 15:34 UTC, nickgw reviewed
Hey, I've made this change but the Unit tests for Computer continue to fail. I'm not certain what I'm doing wrong here, and the test output is not the most helpful.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-:-N-TP2PB90_FEqq8uaRv:b22cxyh)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @nickgw and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-04-13 07:01 UTC, PlagueHO commented
I'll have a look at test failures tomorrow night.

2022-04-20 05:57 UTC, PlagueHO commented
Sorry about the delay in looking at this @nickgw - got a bit snowed under. Will try again tomorrow night.

2022-04-20 14:52 UTC, nickgw commented
> Sorry about the delay in looking at this @nickgw - got a bit snowed under. Will try again tomorrow night.

Thanks, appreciate your time!

2022-04-21 06:15 UTC, PlagueHO requested changes
Ok @nickgw - figured out what was wrong. Have added comments below. Can you also add some tests to cover passing the new parameter to `Test-TargetResource` and `Set-TargetResource`?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-:-N09kVVu5O-BRIXxVje8:btdbw5q)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[tests/Unit/DSC_Computer.Tests.ps1, line 1193 at r8](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N09jrx61eJN5d7a-Qt_:-N09jrx61eJN5d7a-Qta:b9f3pfw) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/d363a85d4d011fd07fa47d01c57c624489e45588/tests/Unit/DSC_Computer.Tests.ps1#L1193)):*
> ```PowerShell
>                         -ArgumentName 'Credential'
> 
>                     Assert-ResourceProperty `
> ```

Doh - Not sure how I missed this. Should be:
```
{
    Assert-ResourceProperty `
        -Name $env:COMPUTERNAME `
        -Options @('PasswordPass', 'UnsecuredJoin') `
        -Credential $machinePassword `
        -Verbose
} | Should -Throw $errorRecord
```
___
*[tests/Unit/DSC_Computer.Tests.ps1, line 1205 at r8](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N09kHXK8SF0LUiYXBFX:-N09kHXK8SF0LUiYXBFY:b-dumzi4) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/d363a85d4d011fd07fa47d01c57c624489e45588/tests/Unit/DSC_Computer.Tests.ps1#L1205)):*
> ```PowerShell
>                         -ArgumentName 'PasswordPass'
> 
>                     Assert-ResourceProperty `
> ```

Should be:
```
{
    Assert-ResourceProperty `
        -Name $env:COMPUTERNAME `
        -Options @('PasswordPass') `
        -Verbose
} | Should -Throw $errorRecord
```


<!-- Sent from Reviewable.io -->

2022-04-23 23:56 UTC, nickgw reviewed
I'm not 100% sure on how I would add tests to Test. The parameter set will validate all the passed options, but test shouldn't do anything else with the Options param otherwise. 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-:-N0Nqa408MC0SQ6m8-zM:br6r72h)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @PlagueHO)

___
*[tests/Unit/DSC_Computer.Tests.ps1, line 1122 at r6](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N-R34hC6WZhbDq1XOYK:-N0NeewQ9m_49dnizqbr:bb6un1j) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9b6136fe1f67dbd3918c897bfc348186ce1ffed3/tests/Unit/DSC_Computer.Tests.ps1#L1122)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Resolved, but tests are still failing
</blockquote></details>

Done
___
*[tests/Unit/DSC_Computer.Tests.ps1, line 1193 at r8](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N09jrx61eJN5d7a-Qt_:-N0Neae8D5G28QNBECL4:b-j687pn) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/d363a85d4d011fd07fa47d01c57c624489e45588/tests/Unit/DSC_Computer.Tests.ps1#L1193)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Doh - Not sure how I missed this. Should be:
```
{
    Assert-ResourceProperty `
        -Name $env:COMPUTERNAME `
        -Options @('PasswordPass', 'UnsecuredJoin') `
        -Credential $machinePassword `
        -Verbose
} | Should -Throw $errorRecord
```
</blockquote></details>

Done. Tests are passing now. 
___
*[tests/Unit/DSC_Computer.Tests.ps1, line 1205 at r8](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N09kHXK8SF0LUiYXBFX:-N0NeQ1J6NyyCUAlroyi:b-j687pn) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/d363a85d4d011fd07fa47d01c57c624489e45588/tests/Unit/DSC_Computer.Tests.ps1#L1205)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be:
```
{
    Assert-ResourceProperty `
        -Name $env:COMPUTERNAME `
        -Options @('PasswordPass') `
        -Verbose
} | Should -Throw $errorRecord
```
</blockquote></details>

Done. Tests are passing now. 


<!-- Sent from Reviewable.io -->

2022-05-10 04:35 UTC, nickgw commented
Hey @PlagueHO, please let me know when you get a chance to review this again!

2022-05-11 04:21 UTC, PlagueHO commented
Hi @nickgw - sorry about the delay. I'll get onto this this weekend (snowed under with day job). I do notice that the code coverage has dropped ag bit - I think it just needs a unit test that covers these two lines: https://codecov.io/gh/dsccommunity/ComputerManagementDsc/compare/f679412af08ac9184692715c3ca105299a47bd7d...322e0c7f987db909d1471128b30952b25661144d/diff#D2-271

2022-05-13 09:09 UTC, PlagueHO requested changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 1 of 3 files at r6, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381)* status: all files reviewed, 8 unresolved discussions (waiting on @nickgw)

___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 272 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wdoeKBe96Uzf8e6KH:-N1wdoeKBe96Uzf8e6KI:b-2c5xjd) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L272)):*
> ```PowerShell
>                     #>
>                     Assert-ResourceProperty @PSBoundParameters
>                     $addComputerParameters.Add("Options", $Options)
> ```

Can you convert the "Options" to single quotes? E.g. `'Options'`
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 761 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1weMmH7q4wfNnNVHCf:-N1weMmH7q4wfNnNVHCg:bv0ax5a) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L761)):*
> ```PowerShell
> 
>     if (
>         ($options -contains 'PasswordPass') -and
> ```

The inner () aren't needed. This should be formatted like this:
```powershell
    if ($options -contains 'PasswordPass' -and
        $options -notcontains 'UnsecuredJoin')
```
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 765 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1we1IbEJmFwLQ0H0wj:-N1we1IbEJmFwLQ0H0wk:bduy1b0) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L765)):*
> ```PowerShell
>     )
>     {
>         New-InvalidArgumentException -Message $script:localizedData.InvalidOptionPasswordPassUnsecuredJoin -ArgumentName 'PasswordPass'
> ```

Can you shorten this line by back-ticking? We try to stay below 100 chars:

```powershell
New-InvalidArgumentException `
    -Message $script:localizedData.InvalidOptionPasswordPassUnsecuredJoin `
    -ArgumentName 'PasswordPass'
```
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 768 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1welGRC3nYHxHhL0Vz:-N1welGRC3nYHxHhL0W-:b-bb729) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L768)):*
> ```PowerShell
>     }
> 
>     if (
> ```

The inner () aren't needed. This should be formatted like this:
```powershell
    if ($options -contains 'PasswordPass' -and
        $options -contains 'UnsecuredJoin')
```
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 773 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wf-C09MS-eOiIISs4:-N1wf-C09MS-eOiIISs5:b-fz00r8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L773)):*
> ```PowerShell
>     )
>     {
>         if ( -not [System.String]::IsNullOrEmpty($Credential.UserName) )
> ```

Could this `if` condition be added to the previous if? E.g.

```powershell
    if ($options -contains 'PasswordPass' -and
        $options -contains 'UnsecuredJoin' -and 
         -not [System.String]::IsNullOrEmpty($Credential.UserName))
```
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 775 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1weHmz4HM40Y-34JLV:-N1weHmz4HM40Y-34JLW:byunqxm) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L775)):*
> ```PowerShell
>         if ( -not [System.String]::IsNullOrEmpty($Credential.UserName) )
>         {
>             New-InvalidArgumentException -Message $script:localizedData.InvalidOptionCredentialUnsecuredJoinNullUsername -ArgumentName 'Credential'
> ```

Can you shorten this line by back-ticking? We try to stay below 100 chars.
___
*[`source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1` line 19 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wfMcs279Tt9U8kmjD:-N1wfMcs279Tt9U8kmjE:bhfhi4x) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1#L19)):*
> ```PowerShell
>     DomainNameAndWorkgroupNameError = Only DomainName or WorkGroupName can be specified at once.
>     ComputerNotInDomainMessage = This machine is not a domain member.
>     InvalidOptionPasswordPassUnsecuredJoin = Domain Join option "PasswordPass" may not be specified if "UnsecuredJoin" is specified.
> ```

Can we use single quotes instead of double quotes here?
___
*[`source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1` line 20 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wfVUoAt-zVOM6I7Cv:-N1wfVUoAt-zVOM6I7Cw:bhfhi4x) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1#L20)):*
> ```PowerShell
>     ComputerNotInDomainMessage = This machine is not a domain member.
>     InvalidOptionPasswordPassUnsecuredJoin = Domain Join option "PasswordPass" may not be specified if "UnsecuredJoin" is specified.
>     InvalidOptionCredentialUnsecuredJoinNullUsername = "Credential" username must be null if "UnsecuredJoin" is specified.
> ```

Can we use single quotes instead of double quotes here?


<!-- Sent from Reviewable.io -->

2022-05-13 09:10 UTC, PlagueHO reviewed
Looking really good @nickgw - just some minor tweaks and unit tests and should be good to go.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-:-N1wfgAW7NCJL4qJH48r:br6vysf)* status: all files reviewed, 8 unresolved discussions (waiting on @nickgw)



<!-- Sent from Reviewable.io -->

2022-05-13 20:07 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @PlagueHO)

___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 272 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wdoeKBe96Uzf8e6KH:-N1z10ig2AX28Ai3dyWu:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L272)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you convert the "Options" to single quotes? E.g. `'Options'`
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 761 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1weMmH7q4wfNnNVHCf:-N1z1-ra74QIEola8Y9d:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L761)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

The inner () aren't needed. This should be formatted like this:
```powershell
    if ($options -contains 'PasswordPass' -and
        $options -notcontains 'UnsecuredJoin')
```
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 765 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1we1IbEJmFwLQ0H0wj:-N1z1-Tz6KvKByi2amL0:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L765)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you shorten this line by back-ticking? We try to stay below 100 chars:

```powershell
New-InvalidArgumentException `
    -Message $script:localizedData.InvalidOptionPasswordPassUnsecuredJoin `
    -ArgumentName 'PasswordPass'
```
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 768 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1welGRC3nYHxHhL0Vz:-N1z0zAr8pkBDEq0q6tV:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L768)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

The inner () aren't needed. This should be formatted like this:
```powershell
    if ($options -contains 'PasswordPass' -and
        $options -contains 'UnsecuredJoin')
```
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 773 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wf-C09MS-eOiIISs4:-N1z0yRZ5xFUEmxLnRhX:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L773)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could this `if` condition be added to the previous if? E.g.

```powershell
    if ($options -contains 'PasswordPass' -and
        $options -contains 'UnsecuredJoin' -and 
         -not [System.String]::IsNullOrEmpty($Credential.UserName))
```
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 775 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1weHmz4HM40Y-34JLV:-N1z0xh67bNYVcB0dF7r:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L775)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you shorten this line by back-ticking? We try to stay below 100 chars.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1` line 19 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wfMcs279Tt9U8kmjD:-N1z0wMe9gzWlIcwZD9a:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1#L19)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we use single quotes instead of double quotes here?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1` line 20 at r11](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-N1wfVUoAt-zVOM6I7Cv:-N1z0w51Cyj-D6r6VG17:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/322e0c7f987db909d1471128b30952b25661144d/source/DSCResources/DSC_Computer/en-US/DSC_Computer.strings.psd1#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we use single quotes instead of double quotes here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 20:09 UTC, nickgw reviewed
Hey @plagueho , really appreciate the time and comments. I _think_ this is all set now! 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-:-N1z1ZYIBzk2phn_ym_g:bnmcaa5)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-05-20 03:57 UTC, PlagueHO commented
Cool - thanks @nickgw - I'll finish review this weekend!

2022-05-23 05:25 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/381#-:-N2jN8V17VBjWB_3u5JP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)



<!-- Sent from Reviewable.io -->

2022-05-23 05:26 UTC, merged

2022-05-27 07:34 UTC, PlagueHO commented
Looks like an intermittent build failure (integration tests on WS2022). So, I've kicked the build again and hopefully will deploy the preview release.