Computer: Delete existing AD Computer object when joining Computer to Domain
dsccommunity/ComputerManagementDsc pull request #386
Opened 2022-05-18 01:01 UTC by nickgw

#### Pull Request (PR) description

When joining a computer to a domain, if a computer object with the same name already exists in the domain it will be deleted.

#### This Pull Request (PR) fixes the following issues

- Fixes #55 
- Fixes #58 

#### Task list

- [ x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2022-05-18 01:04 UTC, nickgw commented on source/DSCResources/DSC_Computer/DSC_Computer.psm1
> -        } `
These changes are the vscode powershell extension so I don't really get why this is being reformatted.

2022-05-21 11:05 UTC, kilasuit commented
@nickgw Please change use of backticks in your code to us splatting instead as per https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2

2022-05-21 13:20 UTC, nickgw commented
> @nickgw Please change use of backticks in your code to us splatting instead as per https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.2

@kilasuit Should be all set now now

2022-05-22 22:34 UTC, kilasuit reviewed
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)



<!-- Sent from Reviewable.io -->

2022-05-22 23:26 UTC, nickgw reviewed
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)



<!-- Sent from Reviewable.io -->

2022-05-23 05:27 UTC, PlagueHO commented
Hi @nickgw - I've merged your other PR (Awesome, thank you), but it's caused some conflicts. Can you resolve?

2022-05-23 14:55 UTC, nickgw commented
> Hi @nickgw - I've merged your other PR (Awesome, thank you), but it's caused some conflicts. Can you resolve?

Hey @PlagueHO , thanks! I've resolved the merge conflicts.

2022-05-23 15:01 UTC, nickgw commented
@PlagueHO I didn't link the issue I was resolving on the other PR correctly. You can close this out: https://github.com/dsccommunity/ComputerManagementDsc/issues/234

2022-05-28 08:46 UTC, PlagueHO requested changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386)* status: all files reviewed, 25 unresolved discussions (waiting on @nickgw)

___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 697 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38iy0U3UHgcJ-JrUuV:-N38iy0U3UHgcJ-JrUuW:b-wm4wz8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L697)):*
> ```PowerShell
> 
>     .PARAMETER Name
>         Name of the computer to search for in the given domain
> ```

Nit, for consistency: Can you add a full stop at the end of this line?
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 700 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38j2Id-U7yLlOri26S:-N38j2Id-U7yLlOri26T:b-wm4wz8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L700)):*
> ```PowerShell
> 
>     .PARAMETER Domain
>         Domain to search
> ```

Nit, for consistency: Can you add a full stop at the end of this line?
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 703 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38j38oANFPra0s4EDU:-N38j38pDwfbAnOcu9rn:b-wm4wz8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L703)):*
> ```PowerShell
> 
>     .PARAMETER Credential
>         Credential to search domain with
> ```

Nit, for consistency: Can you add a full stop at the end of this line?
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 728 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38iYXbEjJJx2DMIP-U:-N38iYXbEjJJx2DMIP-V:b-ftn3dy) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L728)):*
> ```PowerShell
>     $searcher = New-Object -TypeName System.DirectoryServices.DirectorySearcher
>     $searcher.Filter = "(&(objectCategory=computer)(objectClass=computer)(cn=$Name))"
>     if ( $DomainName -notlike "LDAP://*")
> ```

Can you remove space after the `(`?
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 739 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38iXllCMP6fWy3y9GQ:-N38iXlm1CDAtNcM7KPu:b4y6iwy) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L739)):*
> ```PowerShell
>             ArgumentList = @(
>                 $DomainName,
>                 $($Credential.UserName),
> ```

Are the outer braces needed on this line and the next? 

E.g. could this be:
```powershell
            ArgumentList = @(
                $DomainName,
                $Credential.UserName,
                $Credential.GetNetworkCredential().password
            )
```

I could be wrong though...
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 746 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38k22CBET4lIPNxUA0:-N38k22CBET4lIPNxUA1:b-qb9nvu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L746)):*
> ```PowerShell
>         $searchRoot = New-Object @params
>     }
>     catch
> ```

What exceptions are typically handled here? Can we just ditch the whole try/catch and let the exception get handled by the DSC exception handler?
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 760 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38kPE1CGQ2KAF3e_L2:-N38kPE1CGQ2KAF3e_L3:b-wm4wz8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L760)):*
> ```PowerShell
> 
>     .PARAMETER Path
>         Path to Object to delete
> ```

Nit, for consistency: Can you add a full stop at the end of this line?
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 763 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38kPkz7Omjr4_IKqUY:-N38kPkz7Omjr4_IKqUZ:b-wm4wz8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L763)):*
> ```PowerShell
> 
>     .PARAMETER Credential
>         Credential to authenticate to the domain
> ```

Nit, for consistency: Can you add a full stop at the end of this line?
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 786 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38iC0a-41O5RsyCHRy:-N38iC0a-41O5RsyCHRz:b4y6iwy) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L786)):*
> ```PowerShell
>             ArgumentList = @(
>                 $DomainName,
>                 $($Credential.UserName),
> ```

Are the outer braces needed on this line and the next? 

E.g. could this be:
```powershell
            ArgumentList = @(
                $DomainName,
                $Credential.UserName,
                $Credential.GetNetworkCredential().password
            )
```

I could be wrong though...
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 795 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38k0rl7wahm04lwyd9:-N38k0rl7wahm04lwydA:b-qb9nvu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L795)):*
> ```PowerShell
>         $adsiObj.DeleteTree()
>     }
>     catch
> ```

What exceptions are typically handled here? Can we just ditch the whole try/catch and let the exception get handled by the DSC exception handler?
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1286 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38ksRC4e4jArzPaGa4:-N38ksRD11k51b7ZZPz1:bfmaawo) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1286)):*
> ```PowerShell
>                 }
> 
>                 Mock 'New-Object' { New-Object 'fake_adsi_searcher' } `
> ```

Can you use parameter names and remove quotes around command and tweak formatting to align to standards?



_Suggestion:_
```PowerShell
Mock -CommandName New-Object -MockWith {
        New-Object -TypeName 'fake_adsi_searcher'
    } `
    -ParameterFilter {
        $TypeName -and
        $TypeName -eq 'System.DirectoryServices.DirectorySearcher'
    }
```
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1292 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38m0EACtSE8NmAcCew:-N38m0EB86jKn9yBGfCs:b-aqnfuh) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1292)):*
> ```PowerShell
>                     }
> 
>                 It 'Throws if name is to long' {
> ```

Can you verify that the expected error is being thrown? E.g. Check the error message if possible. I'm assuming that this is actually checking the parameter verifiers?

Also, start It block with 'Should' (just a standard we adopted):



_Code snippet:_
```PowerShell
It 'Should throw the expected exception if the name is to long' {
```
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1302 at r5](https://reviewable.io/reviews/dsccommuni [...]

2022-05-31 02:40 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386)* status: 1 of 4 files reviewed, 20 unresolved discussions (waiting on @PlagueHO)

___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 728 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38iYXbEjJJx2DMIP-U:-N3Myn7T3YyeaVfv0Wsy:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L728)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove space after the `(`?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 739 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38iXllCMP6fWy3y9GQ:-N3MyoCA6zkYQwxQctfY:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L739)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Are the outer braces needed on this line and the next? 

E.g. could this be:
```powershell
            ArgumentList = @(
                $DomainName,
                $Credential.UserName,
                $Credential.GetNetworkCredential().password
            )
```

I could be wrong though...
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 746 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38k22CBET4lIPNxUA0:-N3MypK1AsaqzG36Xug6:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L746)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

What exceptions are typically handled here? Can we just ditch the whole try/catch and let the exception get handled by the DSC exception handler?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 786 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38iC0a-41O5RsyCHRy:-N3MysA9209YjAJ8Bj8B:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L786)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Are the outer braces needed on this line and the next? 

E.g. could this be:
```powershell
            ArgumentList = @(
                $DomainName,
                $Credential.UserName,
                $Credential.GetNetworkCredential().password
            )
```

I could be wrong though...
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_Computer/DSC_Computer.psm1` line 795 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38k0rl7wahm04lwyd9:-N3MysrU-C8zNveHSziJ:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/source/DSCResources/DSC_Computer/DSC_Computer.psm1#L795)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

What exceptions are typically handled here? Can we just ditch the whole try/catch and let the exception get handled by the DSC exception handler?
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1286 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38ksRC4e4jArzPaGa4:-N3Myxg07y-gNOMzIVZz:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1286)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use parameter names and remove quotes around command and tweak formatting to align to standards?
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1292 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38m0EACtSE8NmAcCew:-N3MyyOhD8Xi0-_ple9T:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1292)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you verify that the expected error is being thrown? E.g. Check the error message if possible. I'm assuming that this is actually checking the parameter verifiers?

Also, start It block with 'Should' (just a standard we adopted):

</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1302 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38nU-XCjeWYxEiqKua:-N3Myz41-q-boOiUJXTF:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1302)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

It should verify that the expected exception is thrown. Can usually just check the error message if it's mocked, or check the error object if it's a custom exception your code is throwing.
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1313 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38lxp_6dx_YjQO0e8h:-N3MyzUl0F4cDezUieBj:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1313)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove blank line here?
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1314 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38lg4nB0JmjAd35u0Q:-N3Mz-7C5yXwp1UpoLiZ:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1314)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use parameter names and remove quotes around command and tweak formatting to align to standards?
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1330 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38mHUJBZhNX9v9FmBQ:-N3Mz-ZX7RIBY6435MRk:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1330)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you remove blank line here?
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1335 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38mJqR60GKa8UIv4n7:-N3Mz0AxDXQ6LbuMnP7z:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1335)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use parameter names and remove quotes around command and tweak formatting to align to standards?
</blockquote></details>

Done.
___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1346 at r5](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N38nB1V3bEUmuDgen28:-N3Mz0qx5Ke2B097p5SR:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9f7919fd13f600a4a962a4c1a8ab59419184f991/tests/Unit/DSC_Computer.Tests.ps1#L1346)):*
<d [...]

2022-06-01 07:15 UTC, PlagueHO approved these changes
Awesome job @nickgw - just one minor tweak to the CHANGELOG.md to ensure the release process works correctly and then we can merge.

> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-:-N3T6W0d5GJO7D5bWkW2:blb0z8e)* status: all files reviewed, 1 unresolved discussion (waiting on @nickgw)

___
*[`CHANGELOG.md` line 7 at r8](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N3T67DYDuc1EfuhCKAw:-N3T67DZ-1aXws2oPc2D:b-7apaau) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/20df9ddf4aa731dc2e112a2f456dd1242eee84cf/CHANGELOG.md#L7)):*
> ```Markdown
> 
> ## [Unreleased]
> - Computer
> ```

Minor thing I just noticed that might upset the release process: Can you move this down under the ### Added section? Also, can you add a blank line after the ### Added.

E.g.

```markdown
### Added

- Computer
  - Support Options Parameter for domain join - Fixes [Issue #234](https://github.com/dsccommunity/ComputerManagementDsc/issues/234).
  - When joining a computer to a domain, existing AD computer objects will be deleted.
```


<!-- Sent from Reviewable.io -->

2022-06-01 07:16 UTC, PlagueHO approved these changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386)* status: all files reviewed, 2 unresolved discussions (waiting on @nickgw)

___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1356 at r8](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-N3T6fTo5cz8Sa9JOAMs:-N3T6fTp8SUXTB0LQIpl:b6b9u4y) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/20df9ddf4aa731dc2e112a2f456dd1242eee84cf/tests/Unit/DSC_Computer.Tests.ps1#L1356)):*
> ```PowerShell
>                 It 'Should throw the expected exception if Credential is incorrect' {
>                     Mock -CommandName New-Object -MockWith {
>                          Write-Error -message "Invalid Credentials"
> ```

Nit, Doh! Missed one minor thing:

```powershell
Write-Error -Message 'Invalid Credentials'
```


<!-- Sent from Reviewable.io -->

2022-06-02 07:02 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/386#-:-N3YDL63A5hKZdZoKFg3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nickgw)



<!-- Sent from Reviewable.io -->

2022-06-02 07:15 UTC, merged