PSResourceRepository, PSResource: Resources to manage PowerShell Package Repositories and PowerShell Packages
dsccommunity/ComputerManagementDsc pull request #395
Opened 2022-11-02 01:45 UTC by nickgw

#### Pull Request (PR) description

New resources to manage PowerShell repositories and PowerShell modules: 

- `PSResourceRepository`
- `PSResource`

#### This Pull Request (PR) fixes the following issues

- Fixes #393 

#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2022-11-05 19:46 UTC, PlagueHO requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @nickgw)

___
*[`tests/Unit/DSC_Computer.Tests.ps1` line 1407 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NG8K4nNCt7ilgqlzdkq:-NG8K4nO786MxRAh3ps4:b-onqc1h) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/438d2c29a938f1c4e2b5a1e916bd6205fd950c13/tests/Unit/DSC_Computer.Tests.ps1#L1407)):*
> ```PowerShell
>                             -Credential $credential`
>                             -Verbose
>                     } | Should -Throw $message
> ```

I think removing this block has broken the tests. Was that intentional?


<!-- Sent from Reviewable.io -->

2022-11-05 22:45 UTC, nickgw commented
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)_ status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @nickgw)
> 
> _[`tests/Unit/DSC_Computer.Tests.ps1` line 1407 at r2](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NG8K4nNCt7ilgqlzdkq:-NG8K4nO786MxRAh3ps4:b-onqc1h) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/438d2c29a938f1c4e2b5a1e916bd6205fd950c13/tests/Unit/DSC_Computer.Tests.ps1#L1407)):_
> 
> > ```powershell
> >                             -Credential $credential`
> >                             -Verbose
> >                     } | Should -Throw $message
> > ```
> 
> I think removing this block has broken the tests. Was that intentional?

Thanks, don't know how that made it in!

2022-11-12 12:39 UTC, johlju commented
With the latest changes in this PR I can run the resource. Running the below on a lab server with `Invoke-DscResource` (which invokes LCM, so in Windows PowerShell):

```powershell
 Invoke-DscResource -ModuleName ComputerManagementDsc -Name PSResourceRepository -Method Get -Property @{
    Name                      = 'PSGallery'
    SourceLocation            = 'https://www.powershellgallery.com/api/v2'
} -Verbose 
```

```text
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceGet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft
/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQL01 with user sid S-1-5-21-1949799417-2769522740-2476083923-1107.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\
PSModule.psm1'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Getting the current state for resource 'PSResourceRepository' using the key property '{"Nam
e":"PSGallery"}'. (RB0001)
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Return the current state of the repository 'PSGallery'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.0.
0.1\PackageManagement.psd1'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\PackageMan
agement\1.0.0.1\PackageManagement.format.ps1xml'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PackageManagement\1.0.
0.1\Microsoft.PowerShell.PackageManagement.dll'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Find-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Get-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Get-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Get-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Install-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Import-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Find-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Install-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Register-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Save-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Set-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Uninstall-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting cmdlet 'Unregister-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Find-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Find-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Get-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Get-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Get-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Import-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Install-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Install-PackageProvider'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Register-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Save-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Set-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Uninstall-Package'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Importing cmdlet 'Unregister-PackageSource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Publish-Module'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Find-Module'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Save-Module'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Install-Module'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Update-Module'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Uninstall-Module'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Get-InstalledModule'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Find-DscResource'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Find-Command'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Find-RoleCapability'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Publish-Script'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Find-Script'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Save-Script'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Install-Script'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Update-Script'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Uninstall-Script'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Get-InstalledScript'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Register-PSRepository'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Set-PSRepository'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Exporting function 'Unregister-PSRepository'.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Expo [...]

2022-11-19 16:10 UTC, johlju requested changes
I will continue the review tomorrow. I have not started to look at the actual resource code yet. 

> Reviewed 4 of 11 files at r1, 9 of 12 files at r2, 1 of 3 files at r3, 1 of 4 files at r4, 2 of 2 files at r5, 1 of 1 files at r7, 1 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NHFdogw4VHb0ReLNdiU:b-bhhta5)* status: 19 of 26 files reviewed, 4 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/ComputerManagementDsc.psd1` line 24 at r10](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHFbs-V11pbfkAVr7Xn:-NHFbs-V11pbfkAVr7Xo:b-u71z4c) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ddb9b02d545fda8cfbf1dd4210e1e8951a99ccd9/source/ComputerManagementDsc.psd1#L24)):*
> ```PowerShell
> 
>     # Minimum version of the Windows PowerShell engine required by this module
>     PowerShellVersion    = '5.0'
> ```

On second thought I think we should keep this at 4.0 to avoid a breaking change. But we should mention in the resource docs that to use `PSResourceRepository` 5.0 is required.



_Code quote:_
```PowerShell
PowerShellVersion    = '5.0'
```
___
*[`source/prefix.ps1` line 4 at r10](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHFcUT0CgM8BQ7aBtFJ:-NHFcUT0CgM8BQ7aBtFK:b-w15572) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ddb9b02d545fda8cfbf1dd4210e1e8951a99ccd9/source/prefix.ps1#L4)):*
> ```PowerShell
> Import-Module -Name $script:dscResourceCommonModulePath
> 
> # TODO: The goal would be to remove this, when no classes and public or private functions need it.
> ```

We can remove this comment.



_Code quote:_
```PowerShell
# TODO: The goal would be to remove this, when no classes and public or private functions need it.
```
___
*[`source/en-US/ComputerManagementDsc.strings.psd1` line 4 at r10](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHFdHDOCXA9Q3sRUc_L:-NHFdHDOCXA9Q3sRUc_M:b-bd41oz) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ddb9b02d545fda8cfbf1dd4210e1e8951a99ccd9/source/en-US/ComputerManagementDsc.strings.psd1#L4)):*
> ```PowerShell
>     .SYNOPSIS
>         The localized resource strings in English (en-US) for the
>         resource SqlServerDsc module. This file should only contain
> ```

Should be ComputerManagementDsc.



_Code quote:_
```PowerShell
SqlServerDsc
```


<!-- Sent from Reviewable.io -->

2022-11-19 20:06 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 15 of 26 files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/ComputerManagementDsc.psd1` line 24 at r10](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHFbs-V11pbfkAVr7Xn:-NHGUrDP8BRY8M_4v6N2:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ddb9b02d545fda8cfbf1dd4210e1e8951a99ccd9/source/ComputerManagementDsc.psd1#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

On second thought I think we should keep this at 4.0 to avoid a breaking change. But we should mention in the resource docs that to use `PSResourceRepository` 5.0 is required.
</blockquote></details>

Done.
___
*[`source/prefix.ps1` line 4 at r10](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHFcUT0CgM8BQ7aBtFJ:-NHGUl-uD2aNVIAcCTHI:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ddb9b02d545fda8cfbf1dd4210e1e8951a99ccd9/source/prefix.ps1#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this comment.
</blockquote></details>

Done.
___
*[`source/en-US/ComputerManagementDsc.strings.psd1` line 4 at r10](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHFdHDOCXA9Q3sRUc_L:-NHGUoO_2MXGbsKg4qUn:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/ddb9b02d545fda8cfbf1dd4210e1e8951a99ccd9/source/en-US/ComputerManagementDsc.strings.psd1#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should be ComputerManagementDsc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-19 20:25 UTC, johlju commented
@PlagueHO the HQRM test does not pass if minimum PowerShell version is 4.0. So should we 
1. Move to 5.0 and make a breaking change?
2. Keep 4.0 to avoid a breaking change (and document that class-based resources need 5.0) but exclude the tag `Common Tests - Module Manifest` in build.yaml? (and move to 5.0 at a later date)

2022-11-19 21:56 UTC, nickgw commented
> @PlagueHO the HQRM test does not pass if minimum PowerShell version is 4.0. So should we
> 
> 1. Move to 5.0 and make a breaking change?
> 2. Keep 4.0 to avoid a breaking change (and document that class-based resources need 5.0) but exclude the tag `Common Tests - Module Manifest` in build.yaml? (and move to 5.0 at a later date)

fwiw both `DnsServerDsc` and `SqlServerDsc` bumped to 5.0, sql in 2017 and dns when the module was renamed from xdns in 2021 and the first cbr was added.

would wmf4.0 be able to import the module anyway, since `class` was introduced in 5.0?

2022-11-19 22:03 UTC, PlagueHO commented
Yeah, agree! We should bump this to PowerShell 5.0.

We should add a "Requirements" to the README.md. For example: https://github.com/dsccommunity/DFSDsc#requirements

Just make it a breaking change.

2022-11-20 12:02 UTC, johlju requested changes
> Reviewed 1 of 7 files at r10, 2 of 4 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 20 of 26 files reviewed, 22 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`CHANGELOG.md` line 12 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJh8Fe5nvPTxO0dBgd:-NHJh8Fe5nvPTxO0dBge:b-w0dxmm) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/CHANGELOG.md#L12)):*
> ```Markdown
> - PSResourceRepository
>   - New class-based resource to manage PowerShell Resource Repositories - Fixes [Issue #393](https://github.com/dsccommunity/ComputerManagementDsc/issues/393)
> ```

Can we remove this blank line. Otherwise GitHUb will make the entire changelog have a blank line after each entry.
___
*[`CHANGELOG.md` line 19 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJhQic7DJy2l33weEK:-NHJhQic7DJy2l33weEL:b-oylzpk) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/CHANGELOG.md#L19)):*
> ```Markdown
> ### Changed
> 
> - BREAKING CHANGE: PowerShell 5.0 is required.
> ```

Suggest change to 
```
- BREAKING CHANGE: Windows Management Framework 5.0 is required.
```



_Code quote:_
```Markdown
PowerShell 5.0 is required.
```
___
*[`CHANGELOG.md` line 20 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJhgVDBA__mJWGUbBK:-NHJhgVDBA__mJWGUbBL:b-w0dxmm) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/CHANGELOG.md#L20)):*
> ```Markdown
> 
> - BREAKING CHANGE: PowerShell 5.0 is required.
> ```

Can we remove this blank line. Otherwise GitHUb will make the entire changelog have a blank line after each entry.
___
*[`README.md` line 46 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJgj_KA9q2hWe9htTq:-NHJgj_KA9q2hWe9htTr:bnb3byx) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/README.md#L46)):*
> ```Markdown
> - **PowerPlan**: This resource allows specifying a power plan to activate.
> - **PowerShellExecutionPolicy**: Specifies the desired PowerShell execution policy.
> - **PSResourceRepository**: This resource manages PowerShellGet repositories. This resource requires PowerShell version 5.0 and above.
> ```

Don't think we need this sentence since the entire module will not work unless the node is on WMF 5.0, and that is covered in Requirements section.



_Code quote:_
```Markdown
This resource requires PowerShell version 5.0 and above.
```
___
*[`README.md` line 81 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJfrGN35rOo-EdpZO8:-NHJfrGN35rOo-EdpZO9:b-hxmmbq) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/README.md#L81)):*
> ```Markdown
> ## Requirements
> 
> PowerShell 5.0 and above is required for this module because of class based resources.
> ```

As per Daniels comment I suggest we make the requirements more descriptive:

```
## Requirements

### Windows Management Framework 5.0

Required because this module now implements class-based resources.
Class-based resources can only work on computers with Windows
Management Framework 5.0 or above.

### PSResourceRepository

The resource`PSResourceRepository` requires that the PowerShell modules`PowerShellGet` and `PackageManagement` is already present on the target computer.
```



_Code quote:_
```Markdown
PowerShell 5.0 and above is required for this module because of class based resources.

- `PSResourceRepository` requires `PowerShellGet` and `PackageManagement` modules.
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 58 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJiDRVEPW3F4Ri-Hqg:-NHJiDRVEPW3F4Ri-Hqh:b9lui87) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/source/Classes/020.PSResourceRepository.ps1#L58)):*
> ```PowerShell
> 
>     [DscProperty()]
>     [Ensure] $Ensure = [Ensure]::Present
> ```

We should move the parmameter name on a separate line from the type. Throughout the parameters.



_Code quote:_
```PowerShell
$Ensure = [Ensure]::Present
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 67 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJi5LJ-nGcVY3s3oj8:-NHJi5LJ-nGcVY3s3oj9:b-7ifuyc) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/source/Classes/020.PSResourceRepository.ps1#L67)):*
> ```PowerShell
> 
>     [DscProperty()]
>     [pscredential] $Credential
> ```

Missing this parameter in the comment-based help



_Code quote:_
```PowerShell
$Credential
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 116 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJj1ITB7Ooefyk5Zxo:-NHJj1ITB7Ooefyk5Zxp:bnduf22) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/source/Classes/020.PSResourceRepository.ps1#L116)):*
> ```PowerShell
>     hidden [void] SetHiddenProperties()
>     {
>         $repository = Get-PSRepository -Name $this.name -ErrorAction SilentlyContinue
> ```

Upper-case on property name since it is a class parameter/property.



_Suggestion:_
```PowerShell
$this.Name
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 129 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJmuv81vL6ayyaSlxh:-NHJmuv81vL6ayyaSlxi:be0snr5) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/source/Classes/020.PSResourceRepository.ps1#L129)):*
> ```PowerShell
>         if (($properties.Keys -contains 'Ensure') -and ($properties.Ensure -eq 'Absent'))
>         {
>             Write-Verbose -Message ($this.localizedData.RemoveExistingRepository -f $this.Name)
> ```

We should add a blank line after Write-Verbose (to get air in the code)
___
*[`source/Classes/020.PSResourceRepository.ps1` line 131 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJmvoa6bTX6cy96Sw8:-NHJmvoa6bTX6cy96Sw9:b90znds) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/source/Classes/020.PSResourceRepository.ps1#L131)):*
> ```PowerShell
>             Write-Verbose -Message ($this.localizedData.RemoveExistingRepository -f $this.Name)
>             Unregister-PSRepository -Name $this.Name
>             return
> ```

We should add a blank line before `return` (to get air in the code)
___
*[`source/Classes/020.PSResourceRepository.ps1` line 142 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJp_B39Xph43fFqHvc:-NHJp_B39Xph43fFqHvd:b383o4u) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/source/Classes/020.PSResourceRepository.ps1#L142)):*
> ```PowerShell
>             "absent configuration").
>         #>
>         if ($this.Ensure -eq [Ensure]::Present)
> ```

The `$properties` that is passed into `Modify()` only contain those properties not in desired state. Maybe it can simplify logic rather than trying to get the property Registered again and use Registered to know wheter to create the repository or not? 

```
if ($properties.ContainsKey('Ensure') -and $properties.Ensure -eq 'Present' -and $this.Ensure -eq 'Absent')
{
    # Ensure was not in desired state so the repository should be removed
}
elseif ($properties.ContainsKey('Ensure') -and $properties.Ensure -eq 'Absent' -and $this.Ensure -eq 'Present')
{
    # Ensure was not in desired state so the repository should be created
]
else
{
  [...]

2022-11-20 12:04 UTC, johlju commented
@nickgw awesome work on this!  I continue the review when thise comments are resolved. Just tag mig if you want to discuss something.

2022-11-21 20:34 UTC, nickgw commented
Hey @johlju , I think I've resolved / hit all your comments!

2022-11-22 07:34 UTC, johlju commented
@nickgw it seems integration tests for 2019 fails for some reason. It says it doen't found that resource that was run just seconds before. 🙂 I kicked off that job again to see if it fails again. Sometimes the integration tests fail with intermittent errors because we run Set, Get, and Test so quickly after each other...

2022-11-22 07:40 UTC, johlju requested changes
> Reviewed 1 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 18 of 26 files reviewed, 21 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`CHANGELOG.md` line 12 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJh8Fe5nvPTxO0dBgd:-NHTGPS68qlO6YblMnJ4:bvamlg4) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/CHANGELOG.md#L12)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry my bad. Wasn't clear about whar blank line to remove. Make it look like this:

```
### Added

- PSResourceRepository
  - New class-based resource to manage PowerShell Resource Repositories - Fixes [Issue #393](https://github.com/dsccommunity/ComputerManagementDsc/issues/393)
- Computer
  - Support Options Parameter for domain join - Fixes [Issue #234](https://github.com/dsccommunity/ComputerManagementDsc/issues/234).
  - When joining a computer to a domain, existing AD computer objects will be deleted - Fixes [Issue #55](https://github.com/dsccommunity/ComputerManagementDsc/issues/55), [Issue #58](https://github.com/dsccommunity/ComputerManagementDsc/issues/58).

```
___
*[`CHANGELOG.md` line 20 at r12](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHJhgVDBA__mJWGUbBK:-NHTGtN_4x904cAn7e2y:btjchkk) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/9e7d3bd8f9bbe9d2f2346a6042b551e078edf441/CHANGELOG.md#L20)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry my bad. Wasn't clear about whar blank line to remove. Make it look like this:

```
### Changed

- BREAKING CHANGE: Windows Management Framework 5.0 is required.
- ComputerManagementDsc
  - The resource names were removed from the property `DscResourcesToExport`
```


<!-- Sent from Reviewable.io -->

2022-11-22 07:45 UTC, johlju requested changes
Need to continue with the review later. :slightly_smiling_face: 

> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NHTI0_0BhzIGLL3yXqZ:b-rvip60)* status: 19 of 26 files reviewed, 15 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 145 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTHVX59eYIyMz2jp4h:-NHTHVX59eYIyMz2jp4i:br4wcc8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L145)):*
> ```PowerShell
>     #     {
>     #         $this.Registered = $repository.Registered
>     #         $this.Trusted    = $repository.Trusted
> ```

We can remove this if it is no longer used.



_Code quote:_
```PowerShell
    # <#
    #     Set read-only Registered and Trusted properties on PSRepositoryObject
    # #>
    # hidden [void] SetReadProperties()
    # {
    #     $repository = Get-PSRepository -Name $this.Name -ErrorAction SilentlyContinue

    #     if ($repository)
    #     {
    #         $this.Registered = $repository.Registered
    #         $this.Trusted    = $repository.Trusted
    #     }
    # }
```


<!-- Sent from Reviewable.io -->

2022-11-22 08:28 UTC, johlju requested changes
> Reviewed 1 of 7 files at r10, 1 of 6 files at r13.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 26 files reviewed, 15 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 70 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTR9EqDZIAZjdVnTuA:-NHTR9EqDZIAZjdVnTuB:b-glmssv) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L70)):*
> ```PowerShell
>     [DscProperty(Mandatory)]
>     [System.String]
>     $SourceLocation
> ```

We should need to require this property. If the user just want to enforce PublishLocation on an existing repository the user should not need to add the SourceLocation too (it also simplifies when a repository should be absent). We could instead throw an error in Set() if the user tries to create a new repository without the SourceLocation.

What do you think?



_Code quote:_
```PowerShell
    [DscProperty(Mandatory)]
    [System.String]
    $SourceLocation
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 105 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTQFAoEC6UlsTLayJu:-NHTQFAoEC6UlsTLayJv:bp84okh) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L105)):*
> ```PowerShell
> 
>     # [DscProperty(NotConfigurable)]
>     # [System.Boolean]
> ```

We can remove this commented code if it is no longer required.



_Code quote:_
```PowerShell
    # [DscProperty(NotConfigurable)]
    # [System.Boolean]
    # $Trusted

    # [DscProperty(NotConfigurable)]
    # [System.Boolean]
    # $Registered
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 167 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTNaCL0N725J0M_p-y:-NHTNaCL0N725J0M_p-z:b-r59nxq) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L167)):*
> ```PowerShell
>         {
>             # Ensure was not in desired state so the repository should be created
>             $register = $True
> ```

We should use lower-case `t` in `$true`



_Suggestion:_
```PowerShell
$register = $true
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 173 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTNhDe5NMZyp1HiZgz:-NHTNhDe5NMZyp1HiZh-:b-l2dgr9) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L173)):*
> ```PowerShell
>         {
>             # Repository exist but one or more properties are not in desired state
>             $register = $False
> ```

We should use lower-case `f` in `$false`



_Suggestion:_
```PowerShell
$register = $false
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 176 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTO4RE-bHbsHqkPs7d:-NHTO4RE-bHbsHqkPs7e:b-3fcdbx) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L176)):*
> ```PowerShell
>         }
> 
>         foreach ($key in $properties.Keys)
> ```

Maybe we can do this to remove the if-block inside the foreach? 



_Suggestion:_
```PowerShell
foreach ($key in $properties.Keys.Where({ $_ -ne 'Ensure' }))
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 187 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTOVRe83R_H8xKEqte:-NHTOVRe83R_H8xKEqtf:bdwzrn6) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L187)):*
> ```PowerShell
>         if ( $register )
>         {
>             if ($this.Name -eq 'PSGallery')
> ```

Maybe we should only do this (`Register-PSRepository -Default`) if the name is PSGallery and _no other_ properties are set? A user could want to name the repository PSGallery but point the locations to a private repo?



_Code quote:_
```PowerShell
if ($this.Name -eq 'PSGallery')
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 195 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTPY5516kDSJUeoGO9:-NHTPY5516kDSJUeoGOA:bwfrn3g) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L195)):*
> ```PowerShell
>             else
>             {
>                 if (-not ($params.Keys -contains 'SourceLocation'))
> ```

Maybe we can simplify this to be more readable?



_Suggestion:_
```PowerShell
if ($params.Keys -notcontains 'SourceLocation')
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 213 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTPzXQ1zJVRrXM3rUM:-NHTPzXQ1zJVRrXM3rUN:b-h774cq) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L213)):*
> ```PowerShell
> 
> 
>         # if (($properties.Keys -contains 'Ensure') -and ($properties.Ensure -eq 'Absent'))
> ```

Maybe remove commented code here and below if it is no longer necessary?
___
*[`source/Classes/020.PSResourceRepository.ps1` line 292 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTQLJm6X_lbKYy2IvP:-NHTQLJm6X_lbKYy2IvQ:bp84okh) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L292)):*
> ```PowerShell
>             $returnValue.InstallationPolicy        = [InstallationPolicy]::$($repository.InstallationPolicy)
>             $returnValue.PackageManagementProvider = $repository.PackageManagementProvider
>             # $returnValue.Trusted                   = $repository.Trusted
> ```

We can remove this commented code if it is no longer required.



_Code quote:_
```PowerShell
            # $returnValue.Trusted                   = $repository.Trusted
            # $returnValue.Registered                = $repository.Registered
```


<!-- Sent from Reviewable.io -->

2022-11-22 18:37 UTC, nickgw commented
@johlju whenever you get a chance, I've updated / responded to your review!

2022-11-22 19:46 UTC, johlju requested changes
Only need to go through the tests now. Will do as soon as I have time.

> Reviewed 1 of 7 files at r10, 1 of 4 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NHVs85x3xkzbzUn0Cb3:b1njzcv)* status: 22 of 26 files reviewed, 3 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 187 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTOVRe83R_H8xKEqte:-NHVrF_O-2LmnD9289qu:b-llppbr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L187)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Changing PSGallery to anything but the default settings feels like something we should actively discourage and not tacitly allow in the resource. Your call though! I think we should keep as is and let someone open an issue if they want to do bad things like this. 
</blockquote></details>

I see your point, if we should keep this we need to document it, that any properties in the configuration are ignored if the name is PSGallery. @plagueho do you have any thoughts on this?
___
*[`source/Examples/Resources/PSResourceRepository/2-Repository_Absent.ps1` line 18 at r16](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHVqv4k5etT3ZvVq0eM:-NHVqv4k5etT3ZvVq0eN:bv4b7ot) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/66ba546ff8c0784ad40848f903bb1f82feba4b37/source/Examples/Resources/PSResourceRepository/2-Repository_Absent.ps1#L18)):*
> ```PowerShell
>             Name           = 'PSGallery'
>             Ensure         = 'Absent'
>             SourceLocation = 'https://www.powershellgallery.com/api/v2'
> ```

We should be able to remove this from this example now?



_Code quote:_
```PowerShell
SourceLocation = 'https://www.powershellgallery.com/api/v2'
```


<!-- Sent from Reviewable.io -->

2022-11-22 20:08 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 26 files reviewed, 3 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Examples/Resources/PSResourceRepository/2-Repository_Absent.ps1` line 18 at r16](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHVqv4k5etT3ZvVq0eM:-NHVx53D8OIOxX1YPjVB:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/66ba546ff8c0784ad40848f903bb1f82feba4b37/source/Examples/Resources/PSResourceRepository/2-Repository_Absent.ps1#L18)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should be able to remove this from this example now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 20:12 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 26 files reviewed, 3 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 187 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTOVRe83R_H8xKEqte:-NHVxCdT4Doat39XCmGy:b-nbvfwo) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L187)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I see your point, if we should keep this we need to document it, that any properties in the configuration are ignored if the name is PSGallery. @plagueho do you have any thoughts on this?
</blockquote></details>

Er I guess what I meant was registering a repository with the name PSGallery but that isn't the PSGallery seems odd. I don't think we should (and this resource wont) prevent changes to PSGallery, it just wont let you register PSGallery without Default settings. If someone did have a resource like and PSGallery was already absent:

```PSResourceRepository 'PSGallery'
        {
            Name                  = 'PSGallery'
            Ensure                = 'Present'
            InstallationPolicy    = 'Trusted'
            SourceLocation        = 'https://www.mynotdefaultpsgallery.com/api/v2'
            ScriptSourceLocation  = 'https://www.mynotdefaultpsgallery.com/api/v2/package/'
            PublishLocation       = 'https://www.mynotdefaultpsgallery.com/api/v2/items/psscript'
            ScriptPublishLocation = 'https://www.mynotdefaultpsgallery.com/api/v2/package/'
        }```

First DSC run would register default and the second run would update the properties. IDK if we need to call that out or not.
```



<!-- Sent from Reviewable.io -->

2022-11-23 10:46 UTC, johlju reviewed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 22 of 26 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 187 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTOVRe83R_H8xKEqte:-NHZ29XY1QpPgwr4elbK:brm4p3d) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L187)):*
> First DSC run would register default and the second run would update the properties. IDK if we need to call that out or not.

I think we need to call that out if we keep it. :thinking: But I'm thinking that we should not do something else than what the user asks for. With the above example 

* a user would expect that the desired state would be set on the first run. With LCM it would take at least 15 minutes for it to run a second time to be set in desired state
* if running Invoke-DSCResource only once the resource would never be in the desired state.

What if we add an optional parameter `Default`? If the parameter default is used then the repository is registered with defautl values. Then the user can also choose to call the repository something else than PSGallery and still get the default values. :thinking: 


<!-- Sent from Reviewable.io -->

2022-11-23 15:58 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 18 of 27 files reviewed, 2 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 187 at r14](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHTOVRe83R_H8xKEqte:-NH_CFTbAu49wzbZTmCv:bu6qdca) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/535a3b843de88587eac97bae7fe289f9d0e291b6/source/Classes/020.PSResourceRepository.ps1#L187)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The optional parameter `Default` and the location properties (any other?) would ofcourse then be mutually exclusive.
</blockquote></details>

Okay I've hit this, just cleaning up the tests. This feels clunky to me, idk if you have an idea on how to make it cleaner / less painful if we add / remove params: 

```
            if ( $this.SourceLocation -or
                 $this.PackageSourceLocation -or
                 $this.ScriptPublishLocation -or
                 $this.ScriptSourceLocation -or
                 $this.Credential -or
                 $this.PackageManagementProvider -ne 'NuGet'
            )
            {
                $errorMessage = $this.localizedData.DefaultUsedWithOtherParameters

                New-InvalidArgumentException -ArgumentName 'Default' -Message $errorMessage
            }
```


<!-- Sent from Reviewable.io -->

2022-11-23 20:58 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 18 of 27 files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 108 at r19](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NH_PInF7DgWHNtsJS3t:-NHaH34G4TOuMkztKE9w:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/a1de7d7c1e57671999498ab2489c6af33b85b133/source/Classes/020.PSResourceRepository.ps1#L108)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think if we make it nullable and removed the default value it works better with ResourceBase.
</blockquote></details>

Done.
___
*[`source/Classes/020.PSResourceRepository.ps1` line 247 at r19](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NH_Pk3v1cIKfaYYiRRE:-NHaH7HjEjTd4xAOQ6rN:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/a1de7d7c1e57671999498ab2489c6af33b85b133/source/Classes/020.PSResourceRepository.ps1#L247)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should always do the check, regardless of the name of the repository.
</blockquote></details>

Done.
___
*[`source/Classes/020.PSResourceRepository.ps1` line 257 at r19](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NH_OYVEBirZJseFLA7s:-NHaH7_NA4Pi0HKxGnlB:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/a1de7d7c1e57671999498ab2489c6af33b85b133/source/Classes/020.PSResourceRepository.ps1#L257)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There is a common command we can use https://github.com/dsccommunity/DscResource.Common#assert-boundparameter together with `Get-DscProperty`. 

We could change this entire block with something like:

```powershell
$assertBoundParameterParameters = @{
    BoundParameterList = $this | Get-DscProperty -Type @('Key', 'Mandatory', 'Optional') -HasValue
    MutuallyExclusiveList1 = @(
        'Default'
    )
    MutuallyExclusiveList2 = @(
        'SourceLocation'
        'PackageSourceLocation'
        # ... and so on.
    )
}

Assert-BoundParameter @assertBoundParameterParameters
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-25 07:59 UTC, johlju commented
Will continue the review this weekend. 🙂

2022-11-27 16:15 UTC, johlju requested changes
> Reviewed 5 of 7 files at r18, 3 of 4 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 26 of 27 files reviewed, 17 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 48 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtjHjQ0pOBdRBGk72S:-NHtjHjQ0pOBdRBGk72T:b5dw0ss) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L48)):*
> ```PowerShell
>         Default may only be used in conjunction with a PSRepositoryResource named PSGallery.
>         The properties SourceLocation, ScriptSourceLocation, PublishLocation, ScriptPublishLocation, Credential,
>         and PackageManagementProvider may not be used in conjunction with Default.
> ```

We should also mention that the properties are not enforced by the resource when `-Default` is used, if the properties are changed after the repository has been created. If for example a user points SourceLocation to an invalid/non-default URI the resource will not return the repository to desired state when `-Default` is used. 



_Code quote:_
```PowerShell
        The properties SourceLocation, ScriptSourceLocation, PublishLocation, ScriptPublishLocation, Credential,
        and PackageManagementProvider may not be used in conjunction with Default.
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 104 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtmR6y5AYvLLbHYQ3a:-NHtmR6y5AYvLLbHYQ3b:bf5hrf2) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L104)):*
> ```PowerShell
>     [DscProperty()]
>     [InstallationPolicy]
>     $InstallationPolicy = [InstallationPolicy]::Untrusted
> ```

We should not have a default value here (so the deafult is null), because with the defaulkt value it is being enforced when the configuration did not pass it. Looking at verbose output for integration tests for configuration PSResourceRepository_Create_Config.



_Code quote:_
```PowerShell
    $InstallationPolicy = [InstallationPolicy]::Untrusted
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 167 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHthR4H1ZAEiLFq0q-P:-NHthR4H1ZAEiLFq0q-Q:b-hbp9l8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L167)):*
> ```PowerShell
>         foreach ($key in $properties.Keys.Where({ $_ -ne 'Ensure' }))
>         {
>             Write-Verbose -Message ($this.localizedData.PropertyOutOfSync -f $key, $($this.$key))
> ```

Not sure we need this, since I think ResourceBase already write out enough verbose messages that these are not in desired state?



_Code quote:_
```PowerShell
Write-Verbose -Message ($this.localizedData.PropertyOutOfSync -f $key, $($this.$key))
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 253 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtlWPy7Ism53RnPvlX:-NHtlWPy7Ism53RnPvlY:b-yrqshu) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L253)):*
> ```PowerShell
> 
>         $assertBoundParameterParameters = @{
>             BoundParameterList = $this | Get-DscProperty -Type @('Key', 'Mandatory', 'Optional') -HasValue
> ```

Looking at it again we should be able to switch this to `$properties` which holds all the parameters that were specfied. Parent methos Assert() alread ran and passed this for us.



_Code quote:_
```PowerShell
$this | Get-DscProperty -Type @('Key', 'Mandatory', 'Optional') -HasValue
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 10 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtgdQfE24TwvnxlNc6:-NHtgdQfE24TwvnxlNc7:b-r8jqmr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L10)):*
> ```PowerShell
>     GetTargetResourceMessage              = Return the current state of the repository '{0}'.
>     RepositoryNotFound                    = The repository '{0}' was not found.
>     TestTargetResourceMessage             = Determining if the repository '{0}' is in the desired state.
> ```

This string is no longer used, can we remove it?



_Code quote:_
```PowerShell
TestTargetResourceMessage
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 11 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtgsfWAwkirA9uo53F:-NHtgsfWAwkirA9uo53G:b-r8jqmr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L11)):*
> ```PowerShell
>     RepositoryNotFound                    = The repository '{0}' was not found.
>     TestTargetResourceMessage             = Determining if the repository '{0}' is in the desired state.
>     InDesiredState                        = Repository is in the desired state.
> ```

This string is no longer used, can we remove it?



_Code quote:_
```PowerShell
InDesiredState
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 12 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtguLN4F9ej9flofx3:-NHtguLN4F9ej9flofx4:b-r8jqmr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L12)):*
> ```PowerShell
>     TestTargetResourceMessage             = Determining if the repository '{0}' is in the desired state.
>     InDesiredState                        = Repository is in the desired state.
>     NotInDesiredState                     = Repository is not in the desired state.
> ```

This string is no longer used, can we remove it?



_Code quote:_
```PowerShell
NotInDesiredState
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 13 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHth4yC8iuGUsdOUZGG:-NHth4yC8iuGUsdOUZGH:b-r8jqmr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L13)):*
> ```PowerShell
>     InDesiredState                        = Repository is in the desired state.
>     NotInDesiredState                     = Repository is not in the desired state.
>     RepositoryExist                       = Updating the properties of the repository '{0}'.
> ```

This string is no longer used, can we remove it?



_Code quote:_
```PowerShell
RepositoryExist
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 14 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHth6Rt5Pyren37KbOV:-NHth6Rt5Pyren37KbOW:b-r8jqmr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L14)):*
> ```PowerShell
>     NotInDesiredState                     = Repository is not in the desired state.
>     RepositoryExist                       = Updating the properties of the repository '{0}'.
>     RepositoryDoesNotExist                = Creating the repository '{0}'.
> ```

This string is no longer used, can we remove it?



_Code quote:_
```PowerShell
RepositoryDoesNotExist
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 17 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHthF1g3qUiZMb3dxfK:-NHthF1g3qUiZMb3dxfL:b-r8jqmr) ([raw file](https://github.com/dsccommunity/computermanagementd [...]

2022-11-27 16:22 UTC, johlju commented
I saw a couple of strange behaviors in the integration tests, added review comments for them. Maybe I'm to tired and couldn't think straight. 🙂

2022-11-28 15:16 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 23 of 27 files reviewed, 17 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 104 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtmR6y5AYvLLbHYQ3a:-NHyn6L91LcUZCTUOvUp:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L104)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should not have a default value here (so the deafult is null), because with the defaulkt value it is being enforced when the configuration did not pass it. Looking at verbose output for integration tests for configuration PSResourceRepository_Create_Config.
</blockquote></details>

Done.
___
*[`source/Classes/020.PSResourceRepository.ps1` line 167 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHthR4H1ZAEiLFq0q-P:-NHyn81h3b14O3xiqhr5:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L167)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not sure we need this, since I think ResourceBase already write out enough verbose messages that these are not in desired state?
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 10 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtgdQfE24TwvnxlNc6:-NHynR3j4e7qJFWRiaRN:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 11 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtgsfWAwkirA9uo53F:-NHynQvR4Ia8sEISS7uf:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 12 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtguLN4F9ej9flofx3:-NHynQf_-eydgLiyllmo:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 13 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHth4yC8iuGUsdOUZGG:-NHynQTB8oMbMhPWnpUb:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L13)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 14 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHth6Rt5Pyren37KbOV:-NHynQ4z7O3o3gMlbP4P:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 17 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHthF1g3qUiZMb3dxfK:-NHynPbM69dkHTSSNHC1:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L17)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 25 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHti-z98JUOHDMRli2G:-NHynPtG-yfvMUUSO65c:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/en-US/PSResourceRepository.strings.psd1#L25)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 23 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtkZcvCQ0wbW4A-oNM:-NHynbZb5MjD-zArQGyX:b-pv6otj) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L23)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not sure it is a good idea to remove PSGallery as the last thing we do? See also comments in integration tests code.
</blockquote></details>

Do you know of any public PSRepositories I can target rather than just make up URLs? One issue is that `Register-PSRepository` validates URLs so I can just throw fake data at it, which is why I'm touching `PSGallery` so much.


<!-- Sent from Reviewable.io -->

2022-11-28 17:23 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 22 of 27 files reviewed, 17 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 23 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtkZcvCQ0wbW4A-oNM:-NHzFrQ2551o8Q9QVUvt:bjis4er) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L23)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Do you know of any public PSRepositories I can target rather than just make up URLs? One issue is that `Register-PSRepository` validates URLs so I can just throw fake data at it, which is why I'm touching `PSGallery` so much.
</blockquote></details>

Any nuget feed will do. Here are some, where nuget.org is probably the safest. PSGallery Test seems to be offline or they changed URIs.
https://github.com/PowerShell/PowerShellGetv2/pull/426/files#diff-f9c0a3dcb23b60326837be3f9799b237f273acd03fbe0bdfabbee5c4d49602d5R24


<!-- Sent from Reviewable.io -->

2022-11-28 18:12 UTC, kilasuit commented
Honestly not sure that this should be part of this repo and whether or not that @SydneyhSmith & the PowerShellGet team have planned for this in future (as I've been a little outta the loop as of late)

2022-11-28 19:26 UTC, johlju commented
We have thought about that. If that happens, when it is out of preview, that day we can deprecate what this PR proposes. 🙂

2022-11-28 19:57 UTC, johlju commented
@nickgw will continue the review as soon as I have time.

2022-11-28 20:20 UTC, kilasuit commented
@johlju thanks for your comment as that makes things clearer to me & like I said I've been a bit outta the loop for personal reasons this year so thought it only worth a mention just incase it hadn't been thought about, though I perhaps should have trusted a bit more that it would have been, but always better to say something than not do so, right?

2022-11-28 21:55 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 27 files reviewed, 17 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 253 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtlWPy7Ism53RnPvlX:-NI-DOfBCTimC0imjdPu:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L253)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Looking at it again we should be able to switch this to `$properties` which holds all the parameters that were specfied. Parent methos Assert() alread ran and passed this for us.
</blockquote></details>

Done.
___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 10 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtnHhs3Es4aW619zl5:-NI-Demq5h48shndvwB8:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Passing this should have thrown an exception in the integration tests? AssertProperties() should have thrown, right? :thinking: 
</blockquote></details>

Done.
___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 23 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtkZcvCQ0wbW4A-oNM:-NI-EBzhECGZK5Zq4OS9:b-al30a7) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L23)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Any nuget feed will do. Here are some, where nuget.org is probably the safest. PSGallery Test seems to be offline or they changed URIs.
https://github.com/PowerShell/PowerShellGetv2/pull/426/files#diff-f9c0a3dcb23b60326837be3f9799b237f273acd03fbe0bdfabbee5c4d49602d5R24
</blockquote></details>

thanks a bunch! These are exactly what I needed.
___
*[`tests/Integration/Classes/PSResourceRepository.integration.tests.ps1` line 169 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtrEHe6vmmPORhsRlJ:-NI-EIyd5MgLPqsjumrf:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.integration.tests.ps1#L169)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think we should leave PSGallery intact on the build worker so that we do not mess up other pontential tests that need it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-28 22:03 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 27 files reviewed, 17 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 63 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtq_hfEPsg5ZuYwJvp:-NI-G0GTBdSAe5tBTbuR:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L63)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

How does the code find that this property is in desired state... the repositpry doesn't even exist at this point? :thinking: 

```
VERBOSE: [fv-az99-380]:                            [[PSResourceRepository]Integration_Test] MATCH: Value (type 
'System.String') for property 'SourceLocation' does match. Current state is 'https://www.google.com/' and desired state
 is 'https://www.google.com/'. (DRC0020)
```
</blockquote></details>

Done.
___
*[`tests/Integration/Classes/PSResourceRepository.integration.tests.ps1` line 41 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtncNl-OZHUWta72fJ:-NI-FzPY92qBAx_817CW:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.integration.tests.ps1#L41)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Instead of this maybe we can run a test with resource using Absent first? (see also other comment below)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-29 05:55 UTC, johlju requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 171 at r28](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NI0tR3a5H6xHJW7zxVc:-NI0tR3a5H6xHJW7zxVd:bj37yqq) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/59cc4d9e1db145434bc0167f5d3a47f72be75292/source/Classes/020.PSResourceRepository.ps1#L171)):*
> ```PowerShell
>         }
> 
>        if ( $register )
> ```

This line has gotten the wrong identation in a recent commit. :)



_Code quote:_
```PowerShell
if ( $register )
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 12 at r28](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NI0vcya1XZY45jCJ0-j:-NI0vcya1XZY45jCJ0-k:b-r8jqmr) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/59cc4d9e1db145434bc0167f5d3a47f72be75292/source/en-US/PSResourceRepository.strings.psd1#L12)):*
> ```PowerShell
>     RemoveExistingRepository              = Removing the repository '{0}'.
>     ProxyCredentialPassedWithoutProxyUri  = Proxy Credential passed without Proxy Uri.
>     PropertyOutOfSync                     = Repository property '{0}' is not in the desired state, should be '{1}'.
> ```

This string is no longer used, can we remove it?



_Code quote:_
```PowerShell
PropertyOutOfSync
```
___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 10 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtnHhs3Es4aW619zl5:-NI0vnSHBURHkNKRTmMN:b-wcun2p) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L10)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Curious if you found out why the integration tests did not throw when the SourceLocation was present in the integraiton test? 


<!-- Sent from Reviewable.io -->

2022-11-29 06:05 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 10 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtnHhs3Es4aW619zl5:-NI0zJtr3Egf_Srw0NGU:b-f78tz) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Curious if you found out why the integration tests did not throw when the SourceLocation was present in the integraiton test? 
</blockquote></details>

I chalked it up to an old version of the module. Just added an integration to test that this succesfully throws.


<!-- Sent from Reviewable.io -->

2022-11-29 06:06 UTC, nickgw commented
@johlju I'm having trouble figuring out why the integration `PSRepository_Create_Default_Config` is failing on the build runner with 
```
Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'False'; IsRegistered = 'True'.
      [-] Should compile and apply the MOF without throwing 3.14s
        Expected no exception to be thrown, but an exception "Value cannot be null." was thrown from D:\a\1\s\tests\Integration\Classes\PSResourceRepository.integration.tests.ps1:118 char:21
            + ...               Start-DscConfiguration @startDscConfigurationParameters
            +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
        119:                 } | Should -Not -Throw
```

I've run this exact same code on my test machine and it works fine

2022-11-29 06:11 UTC, johlju commented
Guessing it is the line `Register-PSRepository -Default` that fails? Could we add `-Verbose -Debug` to that command to see if we get more output? 
Could it be that we need to pass InstallationPolicy even though it is optional?

Syntax from the help:
```
Register-PSRepository
        [-Default]
        [-InstallationPolicy <String>]
        [-Proxy <Uri>]
        [-ProxyCredential <PSCredential>]
        [<CommonParameters>]
```

2022-11-29 06:18 UTC, johlju commented
Might be something that is different on the build worker. If we can't find it I will try set up an AppVeyor pipeline and see if we can get the same error there. It is posisble to debug (with RDP) on those build workers.

2022-11-29 06:30 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 10 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtnHhs3Es4aW619zl5:-NI13hL1APshBRp07GH9:bupcscq) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L10)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

I chalked it up to an old version of the module. Just added an integration to test that this succesfully throws.
</blockquote></details>

Cool. I just verified it too. Wanted to make sure I had no bug in one of the "generic" functions :slightly_smiling_face: It correctly failed in my tests:
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceGet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft
/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQL01 with user sid S-1-5-21-1949799417-2769522740-2476083923-1107.
VERBOSE: [SQL01]:                            [[PSResourceRepository]DirectResourceAccess] Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\
PSModule.psm1'.
PowerShell DSC resource ComputerManagementDsc  failed to execute Get functionality with error message: None of the parameter(s) 'Default' may be used at the same time as any of the
 parameter(s) 'SourceLocation','PackageSourceLocation','ScriptPublishLocation','ScriptSourceLocation','Credential','PackageManagementProvider'. (DRC0010)
Parameter name: Parameters 
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```


<!-- Sent from Reviewable.io -->

2022-11-29 15:39 UTC, nickgw reviewed
> Might be something that is different on the build worker. If we can't find it I will try set up an AppVeyor pipeline and see if we can get the same error there. It is possible to debug (with RDP, for 60 minutes per run) on those build workers.

I'm assuming I don't have any perms for that, I'd love to try running the config and poking around.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI31AmRCAbQO2TTffN9:b-t3w6b)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 171 at r28](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NI0tR3a5H6xHJW7zxVc:-NI31Q3cCKij7Scvql6P:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/59cc4d9e1db145434bc0167f5d3a47f72be75292/source/Classes/020.PSResourceRepository.ps1#L171)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This line has gotten the wrong identation in a recent commit. :)
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 12 at r28](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NI0vcya1XZY45jCJ0-j:-NI31Vx90Oc3BbnNcHvv:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/59cc4d9e1db145434bc0167f5d3a47f72be75292/source/en-US/PSResourceRepository.strings.psd1#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This string is no longer used, can we remove it?
</blockquote></details>

Done.
___
*[`tests/Integration/Classes/PSResourceRepository.config.ps1` line 63 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NHtq_hfEPsg5ZuYwJvp:-NI31ehi0R0BStjx5QRz:b-tbkep0) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/tests/Integration/Classes/PSResourceRepository.config.ps1#L63)):*
> Data.PSResourceRepository_Modify_Config.SourceLocation
`PSResourceRepository_Modify_Config` is modifying the repository created in `PSResourceRepository_Create_Config`.


<!-- Sent from Reviewable.io -->

2022-11-29 17:11 UTC, nickgw reviewed
FYI, added `-debug -verbose` and we don't get any more output in the CI run. I commented out the `register-psrepository` and `set-psrepository` lines and the issue is with `register-psrepository`. I found this: https://stackoverflow.com/questions/61126168/register-psrepository-throw-error-on-values-cannot-be-found-on-object

I'm thinking TLS1.2 may not be enabled on the builder and the connection test to psgallery's source location is failing.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI3D5WV0pmz7Kbe_tS7:bmj9cqe)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-11-29 17:24 UTC, nickgw reviewed
:thinking: 
```
PS C:\Users\vagrant> [Net.ServicePointManager]::SecurityProtocol
Tls
PS C:\Users\vagrant> Get-PSRepository -Name psgallery
PackageManagement\Get-PackageSource : Unable to find repository 'psgallery'. Use Get-PSRepository to see all available
repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9533 char:35
+ ... ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSource]
   , Exception
    + FullyQualifiedErrorId : SourceNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource

PS C:\Users\vagrant> Register-PSRepository -Default -Verbose
VERBOSE: Performing the operation "Register Module Repository." on target "Module Repository 'PSGallery' () in provider
 'PowerShellGet'.".
PS C:\Users\vagrant> Get-PSRepository
WARNING: Unable to find module repositories.
```

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI3PcNCAcxkQiC1OWgT:b-dt5vva)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-11-29 18:33 UTC, nickgw reviewed
including `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` just before `register-psrepository -default` didn't change anything so :shrug: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI3eVbpEvV-NMMFBT4w:b6v7304)* status: 21 of 27 files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-11-30 14:38 UTC, johlju requested changes
I can try setting up a AppVeyor project and see if the build fails in the same way - but gonna take a day or so. I have another thought. The build worker is using the old PowerShellGet, not the new 2.2.5 I think. I had to tinker with that over at SqlServerDsc to be able to install a preview version. Maybe that is the cause, if you have the newer one locally?

See here what I had to do to get the new 2.2.5 installed on the build worker:

https://github.com/dsccommunity/SqlServerDsc/pull/1808/files#diff-f77d89f77c1da47ff356e302f4deb1bfe94ba9e172c451195fab9e674b241691R301-R325

ANother thought I had. Is it because the resource runs as `SYSTEM`, do you do that on your lab as well, or could it be if we run the resource as a user using `PsDscRunAsCredential` will it work then? 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI6juT18Kz9fNgCDujZ:b-3o4ywf)* status: 21 of 27 files reviewed, 5 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 81 at r31](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NI7y2AcDR8ZcwTbBUPT:-NI7y2AcDR8ZcwTbBUPU:b-cesi4c) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/43ffc82890de3f745f99bd9b2862608dc6d95bc1/source/Classes/020.PSResourceRepository.ps1#L81)):*
> ```PowerShell
>     [DscProperty()]
>     [PSCredential]
>     $Credential
> ```

Should we remove this parameter if the commands that the resources uses cannot use it? 



_Code quote:_
```PowerShell
$Credential
```


<!-- Sent from Reviewable.io -->

2022-11-30 16:09 UTC, nickgw reviewed
SYSTEM on my machine works perfectly. I'll test on 1.0.0.1 PSGet in a moment. Thanks for the link.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI8HvD069Jbomlsnsbc:b-3ecvyp)* status: 21 of 27 files reviewed, 5 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 81 at r31](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NI7y2AcDR8ZcwTbBUPT:-NI8I0Tf4n_D66iGJCY9:b1caq1e) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/43ffc82890de3f745f99bd9b2862608dc6d95bc1/source/Classes/020.PSResourceRepository.ps1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should we remove this parameter if the commands that the resources uses cannot use it? 
</blockquote></details>

Not sure what you mean, `$Credential` is the creds used to access the PSRepository, if required. 


<!-- Sent from Reviewable.io -->

2022-11-30 16:24 UTC, nickgw reviewed
`PowershellGet 1.0.0.1` seems to work fine on my test machine. Let me futz with PackageManagement, too.

```
PS C:\Windows\system32> Get-Module powershellget -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}


PS C:\Windows\system32> Get-PSRepository

PS C:\Windows\system32> Register-PSRepository -Default -Verbose
VERBOSE: Performing the operation "Register Module Repository." on target "Module Repository 'PSGallery' () in provider
 'PowerShellGet'.".
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted =
'False'; IsRegistered = 'True'.
PS C:\Windows\system32> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2
```

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI8LRlD5uvJx5V4KYFp:b-6x28r3)* status: 21 of 27 files reviewed, 5 unresolved discussions (waiting on @johlju and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-11-30 16:54 UTC, nickgw reviewed
Output the versions of psget and packagemanagement: 
```
2022-11-30T16:47:53.6392564Z VERBOSE: [WIN-447ER8DKS53]:                            [[PSResourceRepository]Integration_Test] PowerShellGet version 
2022-11-30T16:47:53.6393487Z 2.2.5 installed
2022-11-30T16:47:53.6405787Z VERBOSE: [WIN-447ER8DKS53]:                            [[PSResourceRepository]Integration_Test] PowerShellGet version 
2022-11-30T16:47:53.6411347Z 1.0.0.1 installed
2022-11-30T16:47:53.6426800Z VERBOSE: [WIN-447ER8DKS53]:                            [[PSResourceRepository]Integration_Test] PackageManagement 
2022-11-30T16:47:53.6427589Z version 1.4.8.1 installed
2022-11-30T16:47:53.6441990Z VERBOSE: [WIN-447ER8DKS53]:                            [[PSResourceRepository]Integration_Test] PackageManagement 
2022-11-30T16:47:53.6445261Z version 1.0.0.1 installed
2022-11-30T16:47:53.6459220Z VERBOSE: [WIN-447ER8DKS53]:                            [[PSResourceRepository]Integration_Test] PowerShellGet version 
2022-11-30T16:47:53.6460639Z 2.2.5 loaded
2022-11-30T16:47:53.6473702Z VERBOSE: [WIN-447ER8DKS53]:                            [[PSResourceRepository]Integration_Test] PackageManagement 
2022-11-30T16:47:53.6476079Z version 1.4.8.1 loaded
```

so `powershellget 2.2.5` and `packagemanagement 1.4.8.1` are being used for the integration tests.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI8SMjWCyY95wRa7wsY:b-a0ofbn)* status: 21 of 27 files reviewed, 5 unresolved discussions (waiting on @johlju and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-11-30 17:17 UTC, nickgw reviewed
I can't reproduce this error. I made sure my test system had the same PSGet and PackageManagement versions and ran the integration tests, all which work perfectly. 

I'm running, just swapping the `$configurationName` variable. This is exactly the integration tests, just with the non-PSGallery integrations and Pester DSL removed: 

```
$ConfigurationData = @{
    AllNodes    = , @{
        NodeName        = 'localhost'
        CertificateFile = $Null
    }
    NonNodeData = @{
        PSResourceRepository_Remove_PSGallery = @{
            Name   = 'PSGallery'
            Ensure = 'Absent'
        }
        PSResourceRepository_Create_Default_Config = @{
            Name    = 'PSGallery'
            Ensure  = 'Present'
            Default = $true
        }
    }
}

<#
    .SYNOPSIS
        Unregister PSRepository PSGallery
#>
configuration PSResourceRepository_Remove_PSGallery
{
    Import-DscResource -ModuleName 'ComputerManagementDsc'

    node $AllNodes.NodeName
    {
        PSResourceRepository 'Integration_Test'
        {
            Name           = $ConfigurationData.NonNodeData.PSResourceRepository_Remove_PSGallery.Name
            Ensure         = $ConfigurationData.NonNodeData.PSResourceRepository_Remove_PSGallery.Ensure
        }
    }
}

<#
    .SYNOPSIS
        Register Default PSRepository PSGallery
#>
configuration PSResourceRepository_Create_Default_Config
{
    Import-DscResource -ModuleName 'ComputerManagementDsc'

    node $AllNodes.NodeName
    {
        PSResourceRepository 'Integration_Test'
        {
            Name    = $ConfigurationData.NonNodeData.PSResourceRepository_Create_Default_Config.Name
            Ensure  = $ConfigurationData.NonNodeData.PSResourceRepository_Create_Default_Config.Ensure
            Default = $ConfigurationData.NonNodeData.PSResourceRepository_Create_Default_Config.Default
        }
    }
}

$testdrive = 'c:\'
$configurationName = 'PSResourceRepository_Create_Default_Config'
$resourceID = '[PSResourceRepository]Integration_Test'

remove-item C:\localhost.mof

$configurationParameters = @{
    OutputPath        = $TestDrive
    ConfigurationData = $ConfigurationData
}

& $configurationName @configurationParameters

$startDscConfigurationParameters = @{
    Path         = $TestDrive
    ComputerName = 'localhost'
    Wait         = $true
    Verbose      = $true
    Force        = $true
    ErrorAction  = 'Stop'
}

Start-DscConfiguration @startDscConfigurationParameters

$script:currentConfiguration = Get-DscConfiguration -Verbose -ErrorAction Stop

$resourceCurrentState = $script:currentConfiguration | Where-Object -FilterScript {
    $_.ConfigurationName -eq $configurationName -and $_.ResourceId -eq $resourceId
}
```

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NI8WxRz9iDd2sBPJYx5:bpwawzy)* status: 21 of 27 files reviewed, 5 unresolved discussions (waiting on @johlju and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-12-03 12:36 UTC, johlju commented
Was busy at work so haven't been able to get back to this. Will setup AppVeyor tomorrow. It seems there is only one issue left with the integration test.

Looking at the verbose output it seems (for one thing) there is an issue with InstallationPolicy. If looking at the test `PSResourceRepository_Remove_PSGallery` at line 440:

https://dev.azure.com/dsccommunity/ComputerManagementDsc/_build/results?buildId=7028&view=logs&j=b097ec3e-ca2c-5821-744b-6fe27b54f344&t=27809048-cd5d-57e6-6d29-c11132922b99&l=440

```
VERBOSE: [WIN-UTBKALQA3RD]:                            [[PSResourceRepository]Integration_Test] NOTMATCH: Value (type 
'InstallationPolicy') for property 'InstallationPolicy' does not match. Current state is '' and desired state is 
'Untrusted'. (DRC0021)
```

In this section of the test it call Get-DscConfiguration to validate current state. What seems to hsappen here is that for some reason Compare() that is called by ResorceBase's Get() function seems to think the configuration contain `InstallationPolicy = 'Untrusted'` which it doesn't. This should not happen since the value for property `InstallationPolicy` should be `$null` if it is not specified in the configuration. So does this happen because the property is using the advanced type based on the enum `InstallationPolicy`, and that type is not nullable? 
If it is not possible to make the advanced typ nullable, will it be resolved if we change the property to use the `string` type and a validate set? See example: https://github.com/dsccommunity/SqlServerDsc/blob/main/source/Classes/002.DatabasePermission.ps1#L38-L41

2022-12-03 12:47 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 27 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 81 at r31](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NI7y2AcDR8ZcwTbBUPT:-NIN0NTF8q4o1KQKPRmN:br1q05h) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/43ffc82890de3f745f99bd9b2862608dc6d95bc1/source/Classes/020.PSResourceRepository.ps1#L81)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Not sure what you mean, `$Credential` is the creds used to access the PSRepository, if required. 
</blockquote></details>

May bad. Couldn't find any other references to the variable thats wayt my comment, but now I found how it is used. Looks good. :slightly_smiling_face: 



_Code quote:_
```PowerShell
$Credential
```


<!-- Sent from Reviewable.io -->

2022-12-04 12:18 UTC, johlju commented
Fixed AppVeyor (and minor tweaks): https://github.com/nickgw/ComputerManagementDsc/pull/2

2022-12-04 13:45 UTC, nickgw commented
>

2022-12-04 14:38 UTC, nickgw commented
hey @johlju thanks for updating that! i'm having trouble finding the rdp output info, though!

2022-12-04 16:58 UTC, johlju commented
Did you create your own free Account on AppVeyor as I mentioned in the PR description in your fork? I also added a comment to the PR here https://github.com/nickgw/ComputerManagementDsc/pull/2#issuecomment-1336398910

2022-12-04 20:40 UTC, nickgw commented
> Did you create your own free Account on AppVeyor as I mentioned in the PR description in your fork? I also added a comment to the PR here [nickgw#2 (comment)](https://github.com/nickgw/ComputerManagementDsc/pull/2#issuecomment-1336398910)

@johlju Thanks, I don't know how I missed the entirety of your PR's description this morning! I was able to get that working, and it also seems your theory about `InstallationPolicy` was correct. All Unit and Integration tests are finally passing now!

2022-12-04 21:11 UTC, nickgw commented
> > Did you create your own free Account on AppVeyor as I mentioned in the PR description in your fork? I also added a comment to the PR here [nickgw#2 (comment)](https://github.com/nickgw/ComputerManagementDsc/pull/2#issuecomment-1336398910)
> 
> @johlju Thanks, I don't know how I missed the entirety of your PR's description this morning! I was able to get that working, and it also seems your theory about `InstallationPolicy` was correct. All Unit and Integration tests are finally passing now!

er spoke too soon... will try and investigate later today.

2022-12-05 19:55 UTC, johlju commented
FYI the commit https://github.com/dsccommunity/ComputerManagementDsc/pull/395/commits/f71e6936acf51201332f26647598cd9c31f7fb51 will only change too 1.0.0.1 in the curremt session of the user (e.g. `AppVeyor`) running Pester tests, not the user (`SYSTEM`) that LCM runs under.

2022-12-05 20:09 UTC, nickgw commented
> FYI the commit [f71e693](https://github.com/dsccommunity/ComputerManagementDsc/commit/f71e6936acf51201332f26647598cd9c31f7fb51) will only change too 1.0.0.1 in the curremt session of the user (e.g. `AppVeyor`) running Pester tests, not the user (`SYSTEM`) that LCM runs under. Not sure what you intention was, but just looked strange so had to comment 🙂

Got it. So, in the appveyor run, I see the error I'm getting in the integration tests with `PowerShellGet 2.2.5`, but not `1.0.0.1`. I dont see the same issue on my personal machine so I'm not exactly sure where to go here. 

I'm spinning up my own 2019 box to see if its a PSGet 2.2.5 & Server2019 issue now.

2022-12-05 20:31 UTC, nickgw commented
```
PS C:\Windows\system32> Get-PSRepository | Unregister-PSRepository
PS C:\Windows\system32> Get-CimInstance win32_operatingsystem

SystemDirectory     Organization   BuildNumber RegisteredUser SerialNumber            Version
---------------     ------------   ----------- -------------- ------------            -------
C:\Windows\system32 gusztavvargadr 17763                      00431-10000-00000-AA740 10.0.17763


PS C:\Windows\system32> Get-Module packagemanagement

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.4.8.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...


PS C:\Windows\system32> Get-Module powershellget

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.5      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...


PS C:\Windows\system32> Register-PSRepository -Default -Verbose
VERBOSE: Performing the operation "Register Module Repository." on target "Module Repository 'PSGallery' () in provider
 'PowerShellGet'.".
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted =
'False'; IsRegistered = 'True'.
```
🤷🏼‍♂️ that's on a 2019 box I just span up with vagrant, so its something specific with the builders, i guess

2022-12-05 20:33 UTC, johlju commented
Are you running that code as the user `SYSTEM` too?

2022-12-05 20:38 UTC, johlju commented
Guessing we just remove the integration test for `Default` then and just keep the one that sets up another repository. 99% of users will probably do just that anyway 🤔
If there are any issues with Default (like we see on the build workers) then that can be solve (or not solved) in another PR.

2022-12-05 20:44 UTC, nickgw commented
> Guessing we just remove the integration test for `Default` then and just keep the one that sets up another repository. 99% of users will probably do just that anyway 🤔 If there are any issues with Default (like we see on the build workers) then that can be solve (or not solved) in another PR.

Agreed. Should I comment the tests out with the reason why we're not running them, or just remove them completely?

2022-12-06 17:47 UTC, johlju commented
> Should I comment the tests out with the reason why we're not running them, or just remove them completely?

I wonder if it is better to open an issue and move the code into the issue so it is being tracked and the code is saved, then we can emove the test code. What do you think? 🤔

2022-12-06 17:54 UTC, johlju requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 28 files reviewed, 3 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 226 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIcYNcQ0zZQoRS2XIBL:-NIcYNcQ0zZQoRS2XIBM:bjjibjo) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L226)):*
> ```PowerShell
>         {
>             $returnValue.Ensure                    = [Ensure]::Present
>             $returnValue.SourceLocation            = $repository.SourceLocation
> ```

I think we should have kept this code, it feels cleaner too. See other comment.



_Suggestion:_
```PowerShell
        if ($repository)
        {
            $returnValue.Ensure                    = [Ensure]::Present
            $returnValue.SourceLocation            = $repository.SourceLocation
            $returnValue.ScriptSourceLocation      = $repository.ScriptSourceLocation


            $returnValue.PublishLocation           = $repository.PublishLocation
            $returnValue.ScriptPublishLocation     = $repository.ScriptPublishLocation
            $returnValue.Proxy                     = $repository.Proxy

            $returnValue.ProxyCredential           = $repository.ProxyCredental
            $returnValue.InstallationPolicy        = $repository.InstallationPolicy
            $returnValue.PackageManagementProvider = $repository.PackageManagementProvider

        }
        else
        {
            Write-Verbose -Message ($this.localizedData.RepositoryNotFound -f $this.Name)
        }
```
___
*[`source/Classes/020.PSResourceRepository.ps1` line 228 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIcYlI70Bi6coyuA8wH:-NIcYlI70Bi6coyuA8wI:by9zup7) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/source/Classes/020.PSResourceRepository.ps1#L228)):*
> ```PowerShell
>         {
>             $returnValue.Ensure = [Ensure]::Present
>             $currentState.Keys | ForEach-Object -Process {
> ```

This just return the state of the parameters passed in the configuration, but if called with Invoke-DscResource we only need to pass `Name` so no other propertes will be returned. Get() should always return all properties (Key, Mandatory, Optional, and Read if exist)

I felt the code you had previously was cleaner and did what was expected. See other comment. Is there a reason for this change?



_Code quote:_
```PowerShell
$currentState.Keys | ForEach-Object -Process {
```


<!-- Sent from Reviewable.io -->

2022-12-06 17:54 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 28 files reviewed, 4 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Enum/2.InstallationPolicy.ps1` line 5 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIcZmOg4XM-jeLF_Dgy:-NIcZmOg4XM-jeLF_Dgz:bez07y9) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/source/Enum/2.InstallationPolicy.ps1#L5)):*
> ```PowerShell
>         The possible states for the DSC resource parameter InstallationPolicy.
> #>
> enum InstallationPolicy
> ```

We can remove this entire file now?



_Code quote:_
```PowerShell
enum InstallationPolicy
```


<!-- Sent from Reviewable.io -->

2022-12-06 18:00 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 28 files reviewed, 10 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`appveyor.yml` line 1 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_otU-e2E6AGblHgn:-NIc_otU-e2E6AGblHgo:bffrdvb) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L1)):*
> ```YAML
> # HOW TO DEBUG: See start of each build run's output how to connect with RDP to the build server for debugging.
> ```

We can keep this file in the repo. It doesn't hurt. But we need to modify it a bit.
___
*[`appveyor.yml` line 3 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_AHg2zZ5UUOV2qjP:-NIc_AHg2zZ5UUOV2qjQ:b-3mhbhv) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L3)):*
> ```YAML
> # HOW TO DEBUG: See start of each build run's output how to connect with RDP to the build server for debugging.
> # See section on_finish last in this file on how to pause build and to keep RDP open.
> # Look for each "DEBUG:"" comment below how to change
> ```

I seemd to have added an extra " here that we can remove.



_Suggestion:_
```YAML
"DEBUG:"
```
___
*[`appveyor.yml` line 26 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_UHq28PvJxBwpguz:-NIc_UHq28PvJxBwpgv-:bhevgd3) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L26)):*
> ```YAML
> - ps: |
>     # Only run for pull requests
>     #if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { Write-Host -ForegroundColor 'Yellow' -Object 'Not a pull request, skipping.'; return }
> ```

Uncomment this row.



_Suggestion:_
```YAML
if
```
___
*[`appveyor.yml` line 34 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_ulz-ghLLCey3a6V:-NIc_ulz-ghLLCey3a6W:bhevgd3) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L34)):*
> ```YAML
> - ps: |
>     # Only run for pull requests
>     #if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { Write-Host -ForegroundColor 'Yellow' -Object 'Not a pull request, skipping.'; return }
> ```

Uncomment this row.



_Suggestion:_
```YAML
if
```
___
*[`appveyor.yml` line 42 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_yJs8zCTzn-DRUUL:-NIc_yJs8zCTzn-DRUUM:bhevgd3) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L42)):*
> ```YAML
> - pwsh: |
>     # Only run for pull requests
>     #if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { Write-Host -ForegroundColor 'Yellow' -Object 'Not a pull request, skipping.'; return }
> ```

Uncomment this row.



_Suggestion:_
```YAML
if 
```
___
*[`appveyor.yml` line 51 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIca-UY-co3W77bTQVy:-NIca-UY-co3W77bTQVz:bhevgd3) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L51)):*
> ```YAML
> - ps: |
>     # Only run for pull requests
>     #if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { Write-Host -ForegroundColor 'Yellow' -Object 'Not a pull request, skipping.'; return }
> ```

Uncomment this row.



_Suggestion:_
```YAML
if
```
___
*[`appveyor.yml` line 62 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIca1Pb8GDGRKNrdhCd:-NIca1Pb8GDGRKNrdhCe:bhevgd3) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L62)):*
> ```YAML
> - ps: |
>     # Only run for pull requests
>     #if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { Write-Host -ForegroundColor 'Yellow' -Object 'Not a pull request, skipping.'; return }
> ```

Uncomment this row.



_Suggestion:_
```YAML
if
```


<!-- Sent from Reviewable.io -->

2022-12-06 18:03 UTC, johlju reviewed
> Reviewed 1 of 4 files at r35.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 22 of 28 files reviewed, 10 unresolved discussions (waiting on @nickgw and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-12-06 18:25 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 28 files reviewed, 10 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`appveyor.yml` line 3 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_AHg2zZ5UUOV2qjP:-NIcf6sz8Y9-09u4kP98:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I seemd to have added an extra " here that we can remove.
</blockquote></details>

Done.
___
*[`appveyor.yml` line 26 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_UHq28PvJxBwpguz:-NIcf7GI6yz4SSLT48XO:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L26)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Uncomment this row.
</blockquote></details>

Done.
___
*[`appveyor.yml` line 34 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_ulz-ghLLCey3a6V:-NIcf7Xp8P009uY4ADJa:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L34)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Uncomment this row.
</blockquote></details>

Done.
___
*[`appveyor.yml` line 42 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIc_yJs8zCTzn-DRUUL:-NIcf7mwBUuQl0YDqBbX:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L42)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Uncomment this row.
</blockquote></details>

Done.
___
*[`appveyor.yml` line 51 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIca-UY-co3W77bTQVy:-NIcf84Q4sWmSGmoJLrS:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L51)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Uncomment this row.
</blockquote></details>

Done.
___
*[`appveyor.yml` line 62 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIca1Pb8GDGRKNrdhCd:-NIcf8KwDBG6O2y4T_98:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/appveyor.yml#L62)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Uncomment this row.
</blockquote></details>

Done.
___
*[`source/Classes/020.PSResourceRepository.ps1` line 228 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIcYlI70Bi6coyuA8wH:-NIcfe5O5Oft3yZWyck_:b-f2sd7y) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/source/Classes/020.PSResourceRepository.ps1#L228)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This just return the state of the parameters passed in the configuration, but if called with Invoke-DscResource we only need to pass `Name` so no other propertes will be returned. Get() should always return all properties (Key, Mandatory, Optional, and Read if exist)

I felt the code you had previously was cleaner and did what was expected. See other comment. Is there a reason for this change?
</blockquote></details>

I think my thought was we should only check the properties that have been explicitly set and not check any of the other properties.

I agree the old function was more readable, I can revert. 
___
*[`source/Enum/2.InstallationPolicy.ps1` line 5 at r41](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIcZmOg4XM-jeLF_Dgy:-NIcfHG_ARqvWPS-aEMi:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/67f459275ddded98ad094e4eb6b175b86da00c62/source/Enum/2.InstallationPolicy.ps1#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this entire file now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-06 18:45 UTC, nickgw commented
> > Should I comment the tests out with the reason why we're not running them, or just remove them completely?
> 
> I wonder if it is better to open an issue and move the code into the issue so it is being tracked and the code is saved, then we can emove the test code. What do you think? 🤔

https://github.com/dsccommunity/ComputerManagementDsc/issues/401

2022-12-06 20:11 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 21 of 28 files reviewed, 10 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 226 at r22](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NIcYNcQ0zZQoRS2XIBL:-NId31Ej8RzpZXbOrKff:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/289c19f0c65f13bdba3ea96c5984d2dc7cdc14ad/source/Classes/020.PSResourceRepository.ps1#L226)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think we should have kept this code, it feels cleaner too. See other comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-07 18:36 UTC, johlju commented
I gonna have a few busy days at work. But after friday I'm off work (vacation) for a month so will continue the review this weekend. 🙂

2022-12-11 14:26 UTC, johlju requested changes
Gone through all the files now. This should hopefully be the last of the comments, or very close to it at least :slightly_smiling_face: 

> Reviewed 1 of 4 files at r30, 1 of 1 files at r42, 1 of 3 files at r43, 3 of 3 files at r44, 3 of 3 files at r45, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NJ0Zuo6E1RpdRr6GEH-:b-csb2ze)* status: all files reviewed, 27 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 181 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0P4Wg8I7MCb1cKnpN:-NJ0P4Wg8I7MCb1cKnpO:b-5gx34t) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/source/Classes/020.PSResourceRepository.ps1#L181)):*
> ```PowerShell
>                 #* The user may have specified Proxy & Proxy Credential, or InstallationPolicy params
>                 Set-PSRepository @params
> ```

We can remove the blank line her
___
*[`source/Classes/020.PSResourceRepository.ps1` line 241 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0PZgh8cnFVm8qoRk5:-NJ0PZgh8cnFVm8qoRk6:bf8kkh5) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/source/Classes/020.PSResourceRepository.ps1#L241)):*
> ```PowerShell
>     }
> 
>     hidden [System.Collections.Hashtable] GetCurrentState1 ([System.Collections.Hashtable] $properties)
> ```

We can now remove this function.



_Code quote:_
```PowerShell
GetCurrentState1
```
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 18 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0Py2REVgu8BlyZsni:-NJ0Py2REVgu8BlyZsnj:b-2fxrl3) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/source/en-US/PSResourceRepository.strings.psd1#L18)):*
> ```PowerShell
>     NoDefaultSettingsPSGallery            = The parameter Default must be set to True for a repository named PSGallery.
>     DefaultSettingsNoPSGallery            = The parameter Default may only be used with repositories named PSGallery.
>     CurrentState                          = Repository '{0}' property '{1}' current state is '{2}'.
> ```

When the function is removed as per previous comment, I think we can remove this localization string also.



_Code quote:_
```PowerShell
CurrentState
```
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 65 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0QYiV336MlHwvrbGt:-NJ0QYiV336MlHwvrbGu:bldev5v) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L65)):*
> ```PowerShell
> 
>     Describe 'PSResourceRepository\Get()' -Tag 'Get' {
> ```

We can remove this blank line
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 69 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0Qf-h1x1Zcp5x9MlY:-NJ0Qf-h1x1Zcp5x9MlZ:bldev5v) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L69)):*
> ```PowerShell
>             Context 'When the repository is Present with default values' {
>                 It 'Should return the correct result when the Repository is present and default params are passed' {
> ```

We can remove this blank line
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 85 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0QlOe6D5MZbVOcnJQ:-NJ0QlOe6D5MZbVOcnJR:b-ylj4xy) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L85)):*
> ```PowerShell
>                         Add-Member -Force -MemberType 'ScriptMethod' -Name 'GetCurrentState' -Value {
>                             return [System.Collections.Hashtable] @{
>                                 Name                      = 'FakePSGallery'
> ```

We should indent this one step to show it is part of the pipeline that is started on the previous line. Throughout the test code on similiar code.



_Code quote:_
```PowerShell
                        Add-Member -Force -MemberType 'ScriptMethod' -Name 'GetCurrentState' -Value {
                            return [System.Collections.Hashtable] @{
                                Name                      = 'FakePSGallery'
                                SourceLocation            = 'https://www.powershellgallery.com/api/v2'
                                Ensure                    = 'Present'
                                InstallationPolicy        = 'Untrusted'
                                PackageManagementProvider = 'Nuget'
                            }
                        } -PassThru |
                        Add-Member -Force -MemberType 'ScriptMethod' -Name 'AssertProperties' -Value {
                            return
                        }
```
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 96 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0RwIs5WWnXoPiac82:-NJ0RwIs5WWnXoPiac83:b-9pjmy8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L96)):*
> ```PowerShell
>                         }
> 
>                         $currentState = $script:mockPSResourceRepositoryInstance.Get()
> ```

Missing the evaluation of the properties `Credential`, `Proxy`, `ProxyCredential`, and `Default` so they return the expected value (`$null`?).



_Code quote:_
```PowerShell
$currentState = $script:mockPSResourceRepositoryInstance.Get()
```
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 138 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0SBC74VKxyyZ-QvKw:-NJ0SBC74VKxyyZ-QvKx:b-9pjmy8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L138)):*
> ```PowerShell
>                         }
> 
>                         $currentState = $script:mockPSResourceRepositoryInstance.Get()
> ```

Missing the evaluation of the properties `Credential`, `Proxy`, `ProxyCredential`, and `Default` so they return the expected value (`$null`?).



_Code quote:_
```PowerShell
$currentState = $script:mockPSResourceRepositoryInstance.Get()
```
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 168 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0Stva3rWupluMmcyG:-NJ0Stva3rWupluMmcyH:b-9pjmy8) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L168)):*
> ```PowerShell
>                             return
>                         }
>                         $currentState = $script:mockPSResourceRepositoryInstance.Get()
> ```

Missing the evaluation of the properties `Credential`, `Proxy`, `ProxyCredential`, and `Default` so they return the expected value (`$null`?).



_Code quote:_
```PowerShell
$currentState = $script:mockPSResourceRepositoryInstance.Get()
```
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 184 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0UXj0ESJnH0ZFWlwJ:-NJ0UXj0ESJnH0ZFWlwK:bldev5v) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L184)):*
> ```PowerShell
>             Context 'When the repository is present but should be absent' {
>                 It 'Should return the correct  [...]

2022-12-11 16:04 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 26 of 29 files reviewed, 27 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`source/Classes/020.PSResourceRepository.ps1` line 181 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0P4Wg8I7MCb1cKnpN:-NJ0dlmZ8HZyQaUkILv_:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/source/Classes/020.PSResourceRepository.ps1#L181)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove the blank line her
</blockquote></details>

Done.
___
*[`source/Classes/020.PSResourceRepository.ps1` line 241 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0PZgh8cnFVm8qoRk5:-NJ0dpvI06z_StE2v_UJ:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/source/Classes/020.PSResourceRepository.ps1#L241)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can now remove this function.
</blockquote></details>

Done.
___
*[`source/en-US/PSResourceRepository.strings.psd1` line 18 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0Py2REVgu8BlyZsni:-NJ0dxmvAUd8nJnfYi2H:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/source/en-US/PSResourceRepository.strings.psd1#L18)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

When the function is removed as per previous comment, I think we can remove this localization string also.
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 65 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0QYiV336MlHwvrbGt:-NJ0e24x7YIeUEenN3PD:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L65)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this blank line
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 69 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0Qf-h1x1Zcp5x9MlY:-NJ0e4la2qUxuArejIPU:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L69)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this blank line
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 85 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0QlOe6D5MZbVOcnJQ:-NJ0eVvQ69NxDOrjlo7X:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L85)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should indent this one step to show it is part of the pipeline that is started on the previous line. Throughout the test code on similiar code.
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 96 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0RwIs5WWnXoPiac82:-NJ0eqqj8ZYXWvb2-AFZ:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L96)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Missing the evaluation of the properties `Credential`, `Proxy`, `ProxyCredential`, and `Default` so they return the expected value (`$null`?).
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 138 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0SBC74VKxyyZ-QvKw:-NJ0ewe2-72-0xqgq-N_:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L138)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Missing the evaluation of the properties `Credential`, `Proxy`, `ProxyCredential`, and `Default` so they return the expected value (`$null`?).
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 168 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0Stva3rWupluMmcyG:-NJ0f-pq7HngHG3dP669:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L168)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Missing the evaluation of the properties `Credential`, `Proxy`, `ProxyCredential`, and `Default` so they return the expected value (`$null`?).
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 184 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0UXj0ESJnH0ZFWlwJ:-NJ0f4hB7BffBNDCdkhU:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L184)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this blank line
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 188 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0Tss2BLYei8Luxu57:-NJ0fB177LG8PYgqz8bB:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L188)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We don't need to provide this when the configuration should be absent.
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 235 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0TLBL-WqKCHNq0TCE:-NJ0fU1b3F4Phzu3b3pQ:byjfb1w) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L235)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

These three should probably return $null since we are mocking the repository to be absent?
</blockquote></details>

The repository is currently Present so Get() is going to populate those keys.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 302 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0TkQi8EZIhzFBcNOe:-NJ0fk3b209OuKputpdL:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L302)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We don't need to provide this when the configuration should be absent.
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 402 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0UEUIBhe41h1I2ad_:-NJ0g2S38T_Hmsnv45YF:b-896fix) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceReposito [...]

2022-12-11 16:04 UTC, nickgw reviewed
I think I just hit everything!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NJ0vV2zB8TZaF_ce8qp:bscnicu)* status: 26 of 29 files reviewed, 27 unresolved discussions (waiting on @johlju and @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-12-11 17:35 UTC, johlju requested changes
Just one more comment.

> Reviewed 2 of 3 files at r46, 1 of 1 files at r47, 1 of 1 files at r48, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NJ1FKue6o5vr0MhBc7l:b-xj7lrj)* status: all files reviewed, 2 unresolved discussions (waiting on @nickgw and @PlagueHO)

___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 235 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0TLBL-WqKCHNq0TCE:-NJ1DNcC0aKRstyl9k85:b-pniac9) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L235)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

The repository is currently Present so Get() is going to populate those keys.
</blockquote></details>

But the It-block description says the current state is absent (repository does not exist in current state), in that case the GetCurrentState would not return the properties. :thinking: Maybe I'm missing something.
___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 494 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0V-mx3kWPFXU6DCOG:-NJ1EY91EHTQ_HdKhmH_:byz6qav) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L494)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

I'm mostly skipping testing these parameters because I'm not sure exactly how `Get-PSRespository` presents them and I can't set up a complicated config like that. IMO, PSRepositories with `ProxyCredential`, `Proxy` or `Credentials` are rare configurations and I'd love to leave them as is in the resource, potentially with an open issue that configurations using those parameters are untested.  
</blockquote></details>

Let us make other contributors create an issue for it if there is an issue. Looks good as-is.


<!-- Sent from Reviewable.io -->

2022-12-11 17:42 UTC, nickgw reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: 28 of 29 files reviewed, 2 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 235 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0TLBL-WqKCHNq0TCE:-NJ1GeCyAFCaFmdb8UzO:b-2okpx4) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L235)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

But the It-block description says the current state is absent (repository does not exist in current state), in that case the GetCurrentState would not return the properties. :thinking: Maybe I'm missing something.
</blockquote></details>

Ah duh. I should have looked a little more closely. My bad mock of `GetCurrentState()` threw me off. This should be fixed now.



_Code quote:_
```PowerShell
hould return the correct result when the Repository is absent but should be present
```


<!-- Sent from Reviewable.io -->

2022-12-11 17:44 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r49, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-:-NJ1HROGCEj004RWs_5L:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[`tests/Unit/Classes/PSResourceRepository.Tests.ps1` line 235 at r45](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395#-NJ0TLBL-WqKCHNq0TCE:-NJ1HOjsAcwB7Wgq0TwR:bk2v9p) ([raw file](https://github.com/dsccommunity/computermanagementdsc/blob/3cba7598bea3da719ebcc103f4ca61d3f7e70ce5/tests/Unit/Classes/PSResourceRepository.Tests.ps1#L235)):*
<details><summary><i>Previously, nickgw (Nick G) wrote…</i></summary><blockquote>

Ah duh. I should have looked a little more closely. My bad mock of `GetCurrentState()` threw me off. This should be fixed now.
</blockquote></details>

No worries :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2022-12-11 17:45 UTC, johlju commented
I will keep an eye on the build jobs en restart them if any fail due to unrelated issues to this PR. 🙂  Then I merge.

2022-12-11 17:52 UTC, johlju approved these changes
> Reviewed 1 of 1 files at r50, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/computermanagementdsc/395)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)



<!-- Sent from Reviewable.io -->

2022-12-11 18:14 UTC, merged

2022-12-11 18:15 UTC, johlju commented
@nickgw awesome work on this! It is now merged. 🙂

2022-12-11 18:38 UTC, nickgw commented
@johlju thanks so much! enjoy your vacation!!!