BREAKING CHANGE: ScheduledTask: Allow better handling of multiple time zones
dsccommunity/ComputerManagementDsc pull request #440
Opened 2024-11-26 16:26 UTC by Borgquite

#### Pull Request (PR) description

Various fixes for StartTime handling in ScheduledTask:
- StartTime is now processed on the device, rather than at compile time. This makes it possible to configure start times based on each device's timezone, rather than being fixed to the time zone configured on the device where the Desired State Configuration compilation was run. This may be a breaking change if people are relying on the old behaviour (configuring all devices based on the *compiling* devices' timezone) - but a fixed offset can still be supplied at compile time, and this new flexibility makes it possible to configure (e.g.) many servers to rotate logs at 12:00:00AM, local time, without knowing their timezones.
- Fixed SynchronizeAcrossTimeZone issue where Test always throws False when a date & time is used where Daylight Savings Time is in operation (#374). We were picking up the current date/time Timezone Offset (zzz) which will not adjust based on the DST of the desired date/time offset.
- Changed the default StartTime date from today to 1st January 1980 to prevent configuration flip flopping, and added note to configuration README to advise always supplying a date, and not just a time.
- Added examples & note to configuration README to supply a timezone when using SynchronizeAcrossTimeZone.
- Allow SynchronizeAcrossTimeZone to be used when adding ScheduleType triggers other than 'Once', 'Daily' and 'Weekly'.
- Updated Test-DateStringContainsTimeZone to process with UTC date strings using Zulu 'Z' string.

#### This Pull Request (PR) fixes the following issues

- Fixes #374
- Fixes #148 
- Fixes #411 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2024-11-28 16:37 UTC, johlju commented
@Borgquite seems the tests fail - guessing you are working on it?

2024-11-28 16:57 UTC, Borgquite commented
@johlju Yes - getting there, I'll post when done :)

2024-11-29 15:05 UTC, Borgquite commented
@PlagueHO @johlju All done, ready for someone to review :)

2024-11-30 03:33 UTC, PlagueHO commented
Oh cool. Let me get onto this tomorrow night

2024-12-02 12:57 UTC, Borgquite commented
@PlagueHO Thanks - let me know how it goes :)

2024-12-12 16:28 UTC, dan-hughes reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Just the one query on the known issue.

> Reviewed 4 of 9 files at r1, 1 of 5 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440#-:-ODvgh3I4ptmWeR2nKVb:b-rde3du)* status: all files reviewed, 1 unresolved discussion (waiting on @Borgquite and @PlagueHO)

___
*[`source/DSCResources/DSC_ScheduledTask/README.md` line 15 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440#-ODvfHya4hLSqmnsoW1T:-ODvfHya4hLSqmnsoW1U:b-wa8pa9) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/1d02de36bb5734796bb229fc26b91edac38027ed/source/DSCResources/DSC_ScheduledTask/README.md#L15)):*
> ```Markdown
> configured on the device. If you want to synchronize a scheduled task across timezones,
> use the SynchronizeAcrossTimeZone parameter, and specify the timezone offset that is needed
> (e.g. 1980-01-01T00:00:00-08:00).
> ```

Should this potentially be enforced to ensure the user does not run into this via another issue maybe?



_Code quote:_
```Markdown
When creating a scheduled task with a StartTime, you should always specify both
a date and a time, with the SortableDateTimePattern format (e.g. 1980-01-01T00:00:00).
Not providing a date may result in 'flip flopping' if the remote server enters daylight
savings time. The date and time specified will be set based on the time zone that has been
configured on the device. If you want to synchronize a scheduled task across timezones,
use the SynchronizeAcrossTimeZone parameter, and specify the timezone offset that is needed
(e.g. 1980-01-01T00:00:00-08:00).
```


<!-- Sent from Reviewable.io -->

2024-12-13 17:44 UTC, dan-hughes commented
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440)_ status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes and @PlagueHO)
> 
> _[`source/DSCResources/DSC_ScheduledTask/README.md` line 15 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440#-ODvfHya4hLSqmnsoW1T:-OE-K96nEhIYRBaXad5l:bqg5zd2) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/1d02de36bb5734796bb229fc26b91edac38027ed/source/DSCResources/DSC_ScheduledTask/README.md#L15)):_
> 
> Previously, dan-hughes (Daniel Hughes) wrote…
> An interesting thought. The difference between a Scheduled Task with SynchronizeAcrossTimeZone enabled, and one without, under the hood appears to be whether it is stored in UTC with the 'Z' offset, or without an offset at all.
> 
> I could see a situation where someone might not want to configure the offset (which, as of this change, should result in a task created using the system's configured timezone) but still wants SATZ enabled - it would work. It would be unusual, but perhaps someone might then want to export the scheduled task to XML and import it to another server, and therefore not defining an offset and SATZ could be desirable, even if very unusual.
> 
> In general I feel that we should only prevent something happening when it will cause an error - not just when it's perhaps 'not recommended'. The current behavior allows what is possible via the user interface (configuring a scheduled task and presuming the local timezone, even with SATZ enabled). I'd probably prefer to leave as-is (advice, not enforced) just in case there are edge cases like the one above where not defining the timezone but still enabling SATZ could be useful.

Makes sense. If someone does want to export and they've configured using DSC, it's not really a typical use case.

@PlagueHO, looks good.

2025-01-22 15:53 UTC, dan-hughes commented
I don't have merge rights.

@PlagueHO, @johlju

2025-01-23 06:51 UTC, PlagueHO commented
Ah right - onto it in 30 minutes!

2025-01-23 07:12 UTC, PlagueHO requested changes
Great stuff @Borgquite , @dan-hughes - just one minor tweak to the CHANGELOG to make it clear that there is a type change.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440#-:-OHH-2XnDXdIfN7Lp21N:b-im13w7)* status: all files reviewed, 2 unresolved discussions (waiting on @Borgquite)

___
*[`CHANGELOG.md` line 48 at r4](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440#-OHGzMra8D-wOMfNe_3M:-OHGzMrb1EqHuT3J0UVH:b-95sqok) ([raw file](https://github.com/dsccommunity/ComputerManagementDsc/blob/1d02de36bb5734796bb229fc26b91edac38027ed/CHANGELOG.md#L48)):*
> ```Markdown
> 
> - BREAKING CHANGE: ScheduledTask
>   - StartTime is now processed on the device, rather than at compile time. This makes it possible
> ```

One final thing: can we note that the StartTime was also changed from DateTime type to String? This is probably not such a problem for PS, but Chef or Puppet or Ansible might be an issue.


<!-- Sent from Reviewable.io -->

2025-01-25 13:46 UTC, johlju approved these changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @Borgquite and @dan-hughes)



<!-- Sent from Reviewable.io -->

2025-01-25 13:47 UTC, johlju commented
I pushed the requested change to the changelog. Will merge as soon as tests pass again.

2025-01-25 14:07 UTC, johlju commented
I am working on a fix for the failing HQRM tests.

2025-01-25 14:25 UTC, johlju reviewed
> Reviewed 4 of 9 files at r1, 1 of 5 files at r2, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @Borgquite and @dan-hughes)



<!-- Sent from Reviewable.io -->

2025-01-25 14:26 UTC, johlju reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440)* status: all files reviewed, 2 unresolved discussions (waiting on @Borgquite)



<!-- Sent from Reviewable.io -->

2025-01-25 14:27 UTC, johlju approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ComputerManagementDsc/440)* status: all files reviewed, 2 unresolved discussions (waiting on @Borgquite)



<!-- Sent from Reviewable.io -->

2025-01-25 14:42 UTC, merged